<?php
	$form = $this->form;
?>
<form class="box login" method="<?php echo $form->getMethod() ?>" action="<?php echo
    $form->getAction()?>">
    <?php
		if(isset($this->success))
		{
		?>
		<fieldset class="boxBody admin">
		<p>Please check your email for the new password and try login again <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"login","action"=>"index"),"default",true)?>" class="rLink">here</a></p>
		</fieldset>
		<?php 
		} else {
	?>
		<fieldset class="boxBody admin">
			<?php
				if(isset($this->errorMessage))
				{
				?>
				<label class="errors"><?php echo $this->errorMessage; ?></label>
				<?php 
				}
			?>
			<?php echo $form->email->renderLabel() ?>
			<?php echo $form->email->renderViewHelper(); ?>
		</fieldset>
		<footer>
			<input type="submit" name="submit" id="submit" value="Reset Password" style="float:right;" />
		</footer>
	<?php 
	}
	?>
</form>