<?php $form = $this->form; ?>
<style type="text/css">
<!--
.logo-box {
	width:600px !important;
}
.logo-box input[type="text"]{
	width:450px !important;
}
.track-url input[type="text"] {
	width:600px !important;
}
-->
</style>
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
          <td align="right"><h2><?php echo $this->language; ?></h2></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditTrack" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php echo $form->module_music_id->renderViewHelper(); ?>
	<?php echo $form->module_music_detail_id->renderViewHelper(); ?>
	<?php echo $form->language_id->renderViewHelper(); ?>
	<table style="margin:10px 0; width:100%;">
		<tbody>
			<tr>
		    	<td><?php echo $form->preview->renderLabel(); ?></td>
		        <td>
		        	<div class="logo-box">
		        		<table width="100%">
		        			<tr>
		        				<td width="5%"><input type="radio" name="preview-option"  id="preview-option-upload" value="upload" /> <label for="preview-option-upload">Upload file:</label></td>
		        				<td><?php echo $form->preview->renderFile(); ?></td>
		        			</tr>
		        			<tr>
		        				<td width="5%" nowrap="nowrap"><input type="radio" name="preview-option" checked="checked" id="preview-option-url" value="url" /> <label for="preview-option-url">or Type the URL:</label></td>
		        				<td><input type="text" name="preview_url" id="preview_url" value="<?php echo $this->preview; ?>" /> </td>
		        			</tr>
		        		</table>
		        	</div>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->artist->renderLabel(); ?></td>
		        <td>
		        	<?php echo $form->artist->renderViewHelper(); ?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->title->renderLabel(); ?></td>
		        <td>
		        	<?php echo $form->title->renderViewHelper(); ?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->album->renderLabel(); ?></td>
		        <td>
		        	<?php echo $form->album->renderViewHelper(); ?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->track_url->renderLabel(); ?></td>
		        <td class="track-url">
		        	<?php echo $form->track_url->renderViewHelper(); ?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->album_art->renderLabel(); ?></td>
		        <td>
		        	<div class="logo-box">
		        		<table width="100%">
		        			<tr>
		        				<td width="5%"><input type="radio" name="album-art-option"  id="album-art-option-upload" value="upload" /> <label for="album-art-option-upload">Upload file:</label></td>
		        				<td><?php echo $form->album_art->renderFile(); ?>(Size: 120px &#215; 120px )</td>
		        			</tr>
		        			<tr>
		        				<td width="5%" nowrap="nowrap"><input type="radio" name="album-art-option" checked="checked" id="album-art-option-url" value="url" /> <label for="album-art-option-upload">or Type the URL:</label></td>
		        				<td><input type="text" name="album_art_url" id="album_art_url" value="<?php echo $this->album_art; ?>" /> </td>
		        			</tr>
		        		</table>
		        	</div>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->status->renderLabel(); ?></td>
		        <td>
		        	<?php echo $form->status->renderViewHelper(); ?>
				</td>
			</tr>
			<tr>
		        <td colspan="3" align="center">
		        	<?php echo $form->submit->renderViewHelper(); ?>&nbsp;
					<?php echo $form->reset->renderViewHelper(); ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$("#frmAddEditTrack").validator().submit(function(e){
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Track...')?>");
	                }
	            });
	            next();
			}).queue(function(next){
				if($('#preview').attr("value")!="") {
					$.ajaxFileUpload({
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:'preview',
						dataType: 'json',
						data:{upload:'preview'},
						success: function (data, status)
						{
							if(data.success != undefined) {
								$("#preview_url").attr("value",data.success);
								next();
							}
						},
						error: function (data, status, e)
						{
							promptus.showErrorMessage("<?php echo $this->translate('Error uploading track.')?>");
							setTimeout(function(){
								promptus.close();
								next();
							}, 2000);
							
						}
					});
				} else {
					next();
				}
			}).queue(function(next){
				if($('#album_art').attr("value")!="") {
					$.ajaxFileUpload({
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:'album_art',
						dataType: 'json',
						data:{upload:'album_art'},
						success: function (data, status)
						{
							if(data.success != undefined) {
								$("#album_art_url").attr("value",data.success);
								next();
							}
						},
						error: function (data, status, e)
						{
							promptus.showErrorMessage("<?php echo $this->translate('Error uploading album art.')?>");
							setTimeout(function(){
								promptus.close();
								next();
							}, 2000);
							
						}
					});
				} else {
					next();
				}
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize(),
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
							next();
						} else if(json["success"] != undefined){
							promptus.showSuccessMessage("<?php echo $this->translate('Track saved successfully.')?>");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"music","controller"=>"index","action" => "index"),"default",true);?>";
							}, 2000);
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
});
// -->
</script>