<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxcore.js"); ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/jqwidget/js/gettheme.js"); ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxdropdownbutton.js"); ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxscrollbar.js"); ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxbuttons.js"); ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxtree.js"); ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxpanel.js"); ?>"></script>
<?php
$data = $this->data;
?>
<form id="frmFilter">
	<div id="filterBox">
		<table
			style="width: 100%; border: 0; border-spacing: 0; border-collapse: collapse;">
			<tr>
				<td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Reorder Cms'); ?></h2></td>
				<td><label for="tree"><?php echo $this->translate('Select Category:'); ?></label></td>
				<td>
					<div id='jqxWidget'>
						<div id="dropDownButton">
							<div id='jqxTree'></div>
						</div>
					</div>
				</td>
				<td align="right"><input type="submit" name="button" id="save-order"
					class="button" value="<?php echo $this->translate('Save')?>" /> <input
					type="reset" name="reset" id="reset" class="button"
					value="<?php echo $this->translate('Reset')?>" />
				</td>
			</tr>
		</table>
	</div>
</form>
<table style="border-spacing: 0; border-collapse: collapse; width: 100%"
	class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
			<th scope="col"><?php echo $this->translate('Title'); ?></th>
			<th scope="col"><?php echo $this->translate('Thumb'); ?></th>
			<th scope="col"><?php echo $this->translate('Status'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php
		foreach ( $data as $row ) {
			?>
			<tr id="index-<?php echo $row["mc.module_cms_id"];?>"
			class="sortable" style="cursor: move;">
			<td><?php echo $row['mcd.title']; ?></td>
			<td><?php echo $row['mcd.thumb']; ?></td>
			<td><?php echo ($row['mc.status']==1)? "Active" : "Inactive"; ?></td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/reorder.js");?>"></script>
<script type="text/javascript">
$(document).ready(function() {
	$(document).on("click","#save-order",function(e){
        var self = this;
        window.currentDeleteUrl = location.href; 
        if(!e.isDefaultPrevented()){
        	var promptus = new prompt({
                    	reference : self,
                        element : "#content",
                        message : "<?php echo $this->translate('Are you sure you want to save page order?'); ?>",
                        buttons : {
                            "Yes" : function(self){
                                var prompt = this;
                                $(document).queue(function(next){
                                    prompt.showLoadingMessage("<?php echo $this->translate('Please wait while saving page order..'); ?>");
                                    next();
                                }).queue(function(next){
                                    $.ajax({
                                        url: window.currentDeleteUrl,
                                        cache: false,
                                        type: "POST",
                                        dataType: "json",
                                        data: serializeOrder(),
                                        success: function(json){
                                            if(json.success != undefined){ 
                                            	prompt.showSuccessMessage("<?php echo $this->translate('Pages reordered successfully.'); ?>");
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 1000);
                                            } else if(json.errors != undefined){
                                                var errorMessage = "<?php echo $this->translate('Unable to reorder pages:'); ?><br />";
                                                errorMessage += json.errors.message;
                                            	prompt.showErrorMessage(errorMessage);
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 2000);
                                            }
                                        },
                                        error: function(){
                                        }
                                    }).complete(next); 
                                });
                            },
                            "No"  : function(self){
                            	this.close();
                            },
                        }
                    });
            e.preventDefault();
        }
    });
    
	$("#reset").on("click", function(){
		location.href = location.href;
	});
	var data = <?php echo $this->parentCategories?>;
	var parentTitle = "<?php echo $this->parentTitle ?>";
	//console.log(data);
	//creating data which jqtree plugin can use
	var builddata = function () {
		var source = [];
		var items = [];
		// build hierarchical source.
		items[0]={id:0,label:'Root Parents'};
		source[0] = items[0];
		for (i = 0; i < data.length; i++) {
			var item = data[i];
			var label = item["text"];
			var parentid = item["parentId"];
			var id = item["id"];

			if (items[parentid]) {
				var item = { id: id, label: label, item: item };
				if (!items[parentid].items) {
					items[parentid].items = [];
				}
				items[parentid].items[items[parentid].items.length] = item;
				items[id] = item;
			}
			else {
				items[id] = { id: id, label: label, item: item };
				source[id] = items[id];
			}
		}		
		return source;
	}
	$("#dropDownButton").jqxDropDownButton({ width: 150, height: 25 });
	$('#jqxTree').bind('initialized', function (event) { 
		var args = event.args;
		//by default form value for parent_id is 0
		//$("#parent_id").attr("value",0);
    	var dropDownContent = '<div style="position: relative; margin-left: 3px; margin-top: 5px;">' + parentTitle + '</div>';
    	$("#dropDownButton").jqxDropDownButton('setContent', dropDownContent);
    });	
	$('#jqxTree').bind('select', function (event) {
        var args = event.args;
        var item = $('#jqxTree').jqxTree('getItem', args.element);
        window.location.href = "<?php echo $this->url(array("module"=>"module-cms","controller"=>"index","action"=>"reorder"),"default",true);?>/id/"+ item.id;
        //selected value of parent_id  
        $("#parent_id").attr("value",item.id);
        var dropDownContent = '<div style="position: relative; margin-left: 3px; margin-top: 5px;">' + item.label + '</div>';
        $("#dropDownButton").jqxDropDownButton('setContent', dropDownContent);        
    });
    var source = builddata();
	$("#jqxTree").jqxTree({source:source,width: 250 });
	$('#jqxTree').jqxTree('expandAll');
});
</script>