<?php 
$form = $this->form; 
$mode = $this->mode;
?>
<script>
window.imagesUploaded = <?php echo $this->imagesUploaded?$this->imagesUploaded:0;?>;
window.imagesLimit = <?php echo $this->imagesLimit?$this->imagesLimit:0;?>;
</script>

<link rel="StyleSheet"
	href="<?php echo $this->baseUrl("libs/tagit/css/jquery.tagedit.css"); ?>"
	type="text/css" media="all" />
<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/tagit/js/jquery.autoGrowInput.js"); ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/tagit/js/jquery.tagedit.js"); ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl("libs/tagit/js/jquery-ui-1.8.6.custom.min.js"); ?>"></script>
<div id="filterBox">
	<table
		style="width: 100%; border: 0; border-spacing: 0; border-collapse: collapse;">
		<tr>
			<td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
			<td align="right"><h2><?php echo $this->language; ?></h2></td>
		</tr>
	</table>
</div>
<div class="boxBorderBottom">
	<form id="frmAddEditimageGallery"
		method="<?php echo $form->getMethod();?>"
		action="<?php echo $form->getAction();?>" class="zend_form">
	<table style="margin: 10px 0;" class="clonedInput" id="input1">
			<tbody>
				<tr>
					<td>
					<?php  echo $form->tag->renderViewHelper();?>	
				<?php  echo $form->module_image_gallery_1_id->renderViewHelper();?>
				<?php  echo $form->language_id->renderViewHelper();?>
				<?php  echo $form->module_image_gallery_detail_1_id->renderViewHelper();?>
					<?php echo $form->module_image_gallery_category_1_id->renderLabel() ?></td>
					<td>
		        	<?php echo $form->module_image_gallery_category_1_id->renderViewHelper()?>
					</td>
				</tr>
				<tr>
					<td><?php echo $form->title->renderLabel() ?></td>
					<td>
		        	<?php echo $form->title->renderViewHelper()?>
					</td>
				</tr>

				<tr>
					<td><label for="image"><?php echo $this->translate('Image'); ?></label></td>
					<td><?php echo $form->image->renderFile();?></td>
					<td><input name="data[1][image_path]" type="hidden" id="image_path1" /></td>
					<td><img src="<?php echo $this->image_thumb?>" height=100 width=100></td>
				</tr>

				<tr>
					<td class="image-label"><?php echo $form->description->renderLabel() ?></td>
					<td>
		        	<?php echo $form->description->renderViewHelper()?>
					</td>
				</tr>

				<tr>
					<td><?php echo $form->status->renderLabel() ?></td>
					<td>
		        	<?php echo $form->status->renderViewHelper()?>
					</td>
				</tr>

				<tr>
					<td><label>Keywords</label></td>
					<td>
					<?php
					if (is_array ( $this->keywords )) {
						foreach ( $this->keywords as $keyword ) {
							?>
								<input type="text" name="arrtag[]"
						value="<?php echo $keyword;?>" class="tag" id="keywords" />
							<?php
						}
					} else {
						?>
						<input type="text" name="data[1][arrtag][]" value="" class="tag" id="keywords" />
					<?php
					}
					?>
				</td>
				</tr>
    			<tr>
    				<td colspan="3" align="center">
    		        	<?php echo html_entity_decode($form->submit->renderViewHelper()) ?>&nbsp;
    		        	<?php echo (Standard_Functions::$action == "edit")? html_entity_decode($form->applyall->renderViewHelper()):""?>&nbsp;
    					<?php echo html_entity_decode($form->reset->renderViewHelper())?>
    				</td>
    			</tr>
			<tbody>
		</table>
	</form>
</div>
<script type="text/javascript">
$("#applyall").on("click",function(e){
	if(!e.isDefaultPrevented()){
    	var promptus = new prompt({
            	reference :"#frmAddEditimageGallery",
                element : "#content",
                message : "<?php echo $this->translate('Your changes will be saved and applied to all languages. Is it Ok?'); ?>",
                buttons : {
                    "Yes" : function(self){
                        this.close();
                        $("#frmAddEditimageGallery").trigger("submit",{all:true});
                    },
                    "No"  : function(self){
                    	this.close();
                    },
                }
            });
        e.preventDefault();
    }
});
function submitForm(e,customObject){
	var promptus = false;
	customObject = customObject || {};
	var queryAppend = "";
	if(customObject.all){
		queryAppend = "&all=true";
	}
	var form = $("#frmAddEditimageGallery");
	if(window.imagesUploaded >= window.imagesLimit){
		 promptus = new prompt({
          reference : "#frmAddEditimageGallery",
          element : "#content"
      });
      promptus.showErrorMessage("You have reached maximum upload image limit of " +window.imagesLimit+ ".Please delete some images and try again");
      setTimeout(function(){
  		promptus.close();
      },2000);
		e.preventDefault();
	}
	if(!e.isDefaultPrevented()){
		var promptus = false;
		$(document).queue(function(next){
			promptus = new prompt({
            	reference : form,
                element : "#content",
                beforeShow : function(){
	                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Image..')?>");
                }
            });
            next();
		}).queue(function(next){
			var imageElements = $("input[type=file][id^=image]");
			var totalImageElements = imageElements.length;
			var initialization = 0;
			var proceed = true;
			imageElements.each(function(key,value){
				if($(this).attr("value")!="") {
					proceed = false;
					var newKey = new Number(key+1);
					$.ajaxFileUpload({	
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:$(this).attr("id"),
						dataType: 'json',
						async : false,
						data:{upload:'true',image_name: $(this).attr("name")},
						success: function (data, status) {
							if(data.success != undefined) {
								$("#image_path"+newKey).attr("value",data.success);
							}
						},
						error: function (data, status, e) {
							promptus.showErrorMessage("<?php echo $this->translate('Error uploading Image.')?>");
							setTimeout(function(){
								promptus.close();
							}, 2000);
							return false;
						},
						complete: function(){
							initialization++;
							if(initialization == totalImageElements) {
								next();
							}
						}
					});
				}
			});
			if(proceed){
				next();
			}
		}).queue(function(next){
			$.ajax({
				type : "POST",
				cache : false,
				data : form.serialize() + queryAppend,
				url : "<?php echo $form->getAction(); ?>",
				success : function(json){
					if(json["errors"] != undefined){
						form.data("validator").invalidate(json["errors"]);
						next();
					} else if(json["success"] != undefined){
						promptus.showSuccessMessage("<?php echo $this->translate('Image saved successfully.')?>");
						setTimeout(function(){
							location.href = "<?php echo $this->url(array("module"=>"module-image-gallery-1","controller"=>"index","action" => "index"),"default",true);?>";
						}, 2000);
					}
				},
				error : next
  			});
		}).queue(function(next){
			promptus.close();
			next();
  		});
		e.preventDefault();
	}
}
$(document).ready(function() {
	$("#frmAddEditimageGallery").validator().submit(function(e,customObject){	
		submitForm(e,customObject);
		});
	
	function initTag(){
	$(function() {
		$( "#frmAddEditimageGallery" ).find('input.tag').tagedit({
				//autocompleteURL: 'server/autocomplete.php'
		});
	});
}
initTag();

});
</script>