<?php $form = $this->form; ?>
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
          <td align="right"><h2><?php echo $this->language; ?></h2></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditHomeWallpaper" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php echo $form->home_wallpaper_id->renderViewHelper();?>
	<?php echo $form->language_id->renderViewHelper();?>
	<?php echo $form->home_wallpaper_detail_id->renderViewHelper();?>
	<table style="margin:10px 0; width:100%;">
		<tbody>
			<tr>
		    	<td><?php echo $form->image_title->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->image_title->renderViewHelper()?>
				</td>
			</tr>
			<?php 
				foreach($this->resolutions as $resolution) {
			?>
			<tr>
				<td></td>
				<td>
					<div class="logo-box">
						<table style="width:100%;">
						<tr>
							<td>
								<label for="image_<?php echo $resolution->getResolutionId(); ?>"><?php echo $resolution->getTitle(); ?></label>
							</td>
							<td>
				        		<input id="image_<?php echo $resolution->getResolutionId(); ?>" type="file" name="image_<?php echo $resolution->getResolutionId(); ?>" />
					        	<input id="image_<?php echo $resolution->getResolutionId(); ?>_path" type="hidden" name="image_<?php echo $resolution->getResolutionId(); ?>_path" value="" />
				        	</td>
				        	<td rowspan="2" align="right">
								<?php 
					        	if(isset($this->image_path[$resolution->getResolutionId()])  && $this->image_path[$resolution->getResolutionId()]!="") {
					        	?>
					        	<img alt="" src="<?php echo  $this->image_path[$resolution->getResolutionId()] ;?>" style="width: 64px;" class="logoImage_<?php echo $resolution->getResolutionId() ?>" />
					        	<a style="margin-right:5px" class="deleteLogo red button-grid" id="<?php echo $resolution->getResolutionId(); ?>">Delete</a>
					        	<?php 
					        	}
					        	?>
				        	</td>
			        	</tr>
			        	<tr>
			        		<td colspan="2" class="desc">
			        			<?php echo $resolution->getDescription()!="" ? "(".$resolution->getDescription().")" : ""; ?>
			        		</td>
			        	</tr>
			        	</table>
		        	</div>
				</td>
			</tr>
			<?php 
				}
			?>
			<tr>
		    	<td><?php echo $form->link_to_module->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->link_to_module->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->status->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->status->renderViewHelper()?>
				</td>
			</tr>
			
			<tr>
		    	<td><?php echo $form->default->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->default->renderViewHelper()?>
				</td>
			</tr>
			
			<tr>
		    	<td></td>
		        <td>
		        	<?php echo $form->submit->renderViewHelper() ?>&nbsp;
		        	<?php echo $form->applyall->renderViewHelper()?>&nbsp;
					<?php echo $form->reset->renderViewHelper() ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$("#applyall").on("click",function(e){
		if(!e.isDefaultPrevented()){
	    	var promptus = new prompt({
	            	reference :"#frmAddEditHomeWallpaper",
	                element : "#content",
	                message : "<?php echo $this->translate('Your changes will be saved and applied to all languages. Is it Ok?'); ?>",
	                buttons : {
	                    "Yes" : function(self){
	                        $("#frmAddEditHomeWallpaper").trigger("submit",{all:true});
	                    },
	                    "No"  : function(self){
	                    	this.close();
	                    },
	                }
	            });
	        e.preventDefault();
	    }
	});
	$(".deleteLogo").on("click",function(){
		var id = $(this).attr("id");
    	$("#image_"+id+"_path").attr("value","deleted");
    	$(".logoImage_"+id).remove();
    	$("#"+id).remove();
    	$("#image_"+id).attr("value","");
    });

	$("#frmAddEditHomeWallpaper").validator().submit(function(e,customObject){
		customObject = customObject || {};
		var queryAppend = "";
		if(customObject.all){
			queryAppend = "&all=true";
		}
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Wallpaper...'); ?>");
	                }
	            });
	            next();
			}).queue(function(next){
				var count = 0;
				$("input[type='file']").each(function(){
					var input = $(this).attr("id");
					if($(this).attr("value") != "")
					{
						$.ajaxFileUpload({
							url:'<?php echo $form->getAction(); ?>',
							secureuri:false,
							fileElementId:$(this).attr("id"),
							dataType: 'json',
							data:{upload:$(this).attr("id")},
							success: function (data, status)
							{
								if(data.success != undefined) {
									$("#"+ input + "_path").attr("value",data.success);
								}	
							},
							complete: function(){
								count++;
								if(count==<?php echo count($this->resolutions);?>){
									next();
								}
							}
						});
					} else {
						count++;
						if(count==<?php echo count($this->resolutions);?>){
							next();
						}
					}
				});
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize() + queryAppend,
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
						} else if(json["success"] != undefined){
							promptus.showSuccessMessage("<?php echo $this->translate('Home Wallpaper saved successfully.'); ?>");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"home-wallpaper","controller"=>"index","action" => "index"),"default",true);?>";
							}, 2000);
						}
						next();
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
});
// -->
</script>