<?php
class ModuleImageGallery_Model_Mapper_ModuleImageGalleryCategoryDetail extends Standard_ModelMapper{
	protected $_dbTableClass = "ModuleImageGallery_Model_DbTable_ModuleImageGalleryCategoryDetail";
}