<ul class="crumbs">
	<?php
	$class = 'class="first"';
	$i = 0;
	foreach ( $this->pages as $index => $page ) {
		echo '<li ' . $class . '>';
		$class = "";
		$style = " style='z-index:" . (count ( $this->pages ) - $i ++) . "' ";
		if (count ( $this->pages ) != $i) {
			echo '<a href="' . $page->getHref () . '" ' . $style . '><span></span>' . $this->translate($page->getLabel ()) . '</a>';
		} else {
			echo '<a href="javascript:void(0);" class="active" ' . $style . '><span></span>' . $this->translate($page->getLabel ()) . '</a>';
		}
		echo "</li>";
	}
	?>
</ul>