<?php
$class = 'class="first"';
$i = 0;
echo '<ul id="menu">';
foreach ( $this->container as $index => $page ) {
	if($page->isVisible() && $this->navigation()->getAcl()->isAllowed($this->navigation()->getRole(),$page->getResource())) {
		$class = "";
		$dropdown = "";
		$properties = new Zend_Config($page->GetCustomProperties());
		if(isset($properties->dropdown))
		{
			$dropdown = $properties->dropdown;
			echo '<li>';
		} else {
			echo '<li class="no-drop">';
		}
		echo '<a href="' . $page->getHref () . '" ' . $class . '>' . $this->translate($page->getLabel ()) . '</a>';
		
		$submenu = array();
		foreach($page->pages as $subPage) {
			$title = "";
			$icon = "";
			$properties = new Zend_Config($subPage->GetCustomProperties());
			if(isset($properties->MM_description)) $title = $properties->MM_description;
			if(isset($properties->MM_icon) && $properties->MM_icon!="") {
				$icon = "<img src='".$this->baseUrl("resource/default/images/icon/".$properties->MM_icon)."' width='20' />";
			} else {
				$icon = "<img src='".$this->baseUrl("images/settings.png")."' width='20' />";
			}
			if($subPage->isVisible() && $this->navigation()->getAcl()->isAllowed($this->navigation()->getRole(),$subPage->getResource())) {
				$submenu[] = $icon.'<a href="' . $subPage->getHref () . '" title="'.$title.'">' . $this->translate($subPage->getLabel ()) . '</a>';
			}
		}
		
		if(count($submenu)>0) {
			if($dropdown == "3columns") {
				$submenu_chunk = array_chunk($submenu, ceil(count($submenu)/3));
				echo '<div class="dropdown_3columns">';
					echo '<div class="col_3"><h2>'.$this->translate($page->getLabel ()).'</h2></div>';
					foreach($submenu_chunk as $chunk) {
						echo "<div class='col_1'><ul class='greybox'><li>". implode("</li><li>", $chunk) ."</li></ul></div>";
					}
				echo'</div>';
			} else if($dropdown == "1columns") {
				echo '<div class="dropdown_1column">';
				echo "<div class='col_1'><ul class='simple'><li>". implode("</li><li>", $submenu) ."</li></ul></div>";
				echo'</div>';
			}
		} else {
			// Future urpose is description require on hover
		}
		echo "</li>";
	}
}
echo "</ul>";
?>