<p>Dear User,</p>
<p>Our records show that on {DATETIME}, you changed your <strong>AppStart</strong> Password.</p>
<table style="font-size: 12px; width: 100%;">
<tbody>
<tr>
<td><strong>New Password:</strong></td>
<td>{PASSWORD}</td>
</tr>
</tbody>
</table>
<p>Please keep your new Password secure.</p>
<p>If this activity occurred without your knowledge or permission. Please reset your password <a href="{RESET_URL}">here</a> if this was an unauthorized change.</p>