<p>Dear User,</p>
<p>Our records show that on {DATETIME}, you changed your <strong>AppStart</strong> Password.</p>

<table width="100%" style="font-size: 12px">
	<tr>
		<td><strong>New Password:</strong>
		</td>
		<td>{PASSWORD}</td>
	</tr>
</table>

<p>Please keep your new Password secure.</p>
<p>If this activity occurred without your knowledge or permission. Please reset your password <a href="{URL}">here</a> if this was an unauthorized change.</p>