<?php $form = $this->form; ?>
<style>

</style>
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
          <td align="right"><h2><?php echo $this->language; ?></h2></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditPushMessage" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php  echo $form->push_message_id->renderViewHelper();?>
	<?php  echo $form->language_id->renderViewHelper();?>
	<?php  echo $form->push_message_detail_id->renderViewHelper();?>
	
	<table style="margin:10px 0;">
		<tbody>
			
			<tr>
		    	<td><?php echo $form->title->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->title->renderViewHelper()?>
				</td>
			</tr>
			
			<tr>
				<td valign="top">
					<label><?php echo $this->translate('Icon:')?></label>
				</td>
				<td valign="top">
					<div id="lstLogo" class="logo-box">
        				<?php $resource_path = $this->baseUrl("resource/push-message/preset-icons");?>
        				<?php foreach ($this->iconpack as $icon):?>
        				<div class="">
							<label for="selLogo_<?php echo $icon; ?>">
								<img src="<?php echo $resource_path . "/" . $icon; ?>" width="64" />
							</label>
							<input type="radio" id="selLogo_<?php echo $icon; ?>" name="selLogo" value="<?php echo $icon; ?>" />
						</div>
        				<?php endforeach;?>
					</div>
				</td>
			</tr>
			
			<tr>
		        <td>&nbsp;</td>
			    <td>
		        	<div class="logo-box">
		        		<table>
						<tr>
							<td>
								<?php 
								$icon_path = $this->baseUrl("resource/push-message/");
					        	if($this->icon_src!="") {
					        	?>
					        	<img alt="" src="<?php echo $icon_path."/".$this->icon_src;?>" style="width: 64px;" />
					        	<?php 
					        	}
					        	?>
				        	</td>
				        	<td>
				        		<?php
				        		$checked = "";
					        	if($this->icon_src!="") {
					        		$checked = "checked='checked'";
								}
								?>
					        	
								<input type="radio" id="selLogo_0" checked="checked" name="selLogo" value="0" style="margin-left: 10px;" />
								<label for="selLogo_0"><?php echo $this->translate('Upload:')?></label>
								<input id="icon" type="file" name="icon" /> (Size: 120px &#215; 120px )
					        	<input id="icon_path" type="hidden" name="icon_path" value="" />
				        	</td>
			        	</tr>
			        	</table>
					</div>
				</td>
			</tr>
			
			<tr>
		    	<td><?php echo $form->description->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->description->renderViewHelper()?>
				</td>
			</tr>
			<tr>
				<td><?php echo $form->message_date->renderLabel() ?></td>
				<td><?php echo $form->message_date->renderViewHelper() ?></td>
			</tr>
			<tr>
		    	<td><?php echo $form->status->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->status->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td></td>
		        <td>
		        	<?php echo $form->submit->renderViewHelper() ?>&nbsp;
		        	<?php echo $form->applyall->renderViewHelper()?>&nbsp;
					<?php echo $form->reset->renderViewHelper() ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$("#applyall").on("click",function(e){
		if(!e.isDefaultPrevented()){
	    	var promptus = new prompt({
	            	reference :"#frmAddEditPushMessage",
	                element : "#content",
	                message : "<?php echo $this->translate('Your changes will be saved and applied to all languages. Is it Ok?'); ?>",
	                buttons : {
	                    "Yes" : function(self){
	                    	this.close();
	                        $("#frmAddEditPushMessage").trigger("submit",{all:true});
	                    },
	                    "No"  : function(self){
	                    	this.close();
	                    },
	                }
	            });
	        e.preventDefault();
	    }
	});
	$("#description").on("keydown",function(){
		if($("#description").attr("value").length>=255) return false;
	});
	$("#description").on("keyup",function(){
		if($("#description").attr("value").length>=255){
			alert('Not more than 255 chars Please');
		$("#description").attr("value","");
		}

	});
	$("input:radio[name=selLogo]").on("change",function(){
		if($('input:radio[name=selLogo]:checked').val() == 0)
		{
			$("#icon").removeAttr("disabled");
		} else {
			$("#icon").attr("disabled","disabled");
		}			
	});
	$('#message_date').datetimepicker({ 
		showOn: "both",
		buttonImage: "<?php echo $this->baseUrl("images/calander.png");?>",
		buttonImageOnly: true,
		dateFormat: 'dd/mm/yy', 
		showSecond: false,
		timeFormat: 'hh:mm',
		firstDay:1
	});
	$("#frmAddEditPushMessage").validator().submit(function(e,customObject){
		customObject = customObject || {};
		var queryAppend = "";
		if(customObject.all){
			queryAppend = "&all=true";
		}
		var form = $(this);
		var self = this;
		if(!e.isDefaultPrevented()){
			promptus = new prompt({
            	reference : form,
                element : "#frmAddEditPushMessage",
                message : "Module will be published automatically. Message will be saved. Are you ok with it?",
                buttons : {
                	"YES" : function(self){
                		var prompt = this;
                            $(document).queue(function(next){
                                prompt.showLoadingMessage("<?php echo $this->translate('Please wait while saving Message..'); ?>");
                                next();
                            }).queue(function(next){
                				if($('input:radio[name=selLogo]:checked').val() == 0 && $('#icon').attr("value")!="") {
                					$.ajaxFileUpload({
                						url:'<?php echo $form->getAction(); ?>',
                						secureuri:false,
                						fileElementId:'icon',
                						dataType: 'json',
                						data:{iconupload:'true'},
                						success: function (data, status)
                						{
                							if(data.success != undefined) {
                								$("#icon_path").attr("value",data.success);
                								next();
                							}
                						},
                						error: function (data, status, e)
                						{
                							promptus.showErrorMessage("<?php echo $this->translate('Error uploading icon.')?>");
                							setTimeout(function(){
                								promptus.close();
                							}, 2000);
                							
                						}
                					});
                				} else {
                					next();
                				}
                			}).queue(function(next){
                            	jQuery.ajax({
								url: "<?php echo $this->url(array("module"=>"push-message","controller"=>"index","action"=>"save"),null,true); ?>",
								type:"POST",
								dataType:"json",
								data:form.serialize() + queryAppend,
								success:function(data){
									if(!data.error)
									{
										promptus.showSuccessMessage("<?php echo $this->translate('Message saved successfully.')?>");
						            	setTimeout(function(){
						            		promptus.close();
						            		location.href = "<?php echo $this->url(array("module"=>"push-message","controller"=>"index","action"=>"index"),"default",true); ?>";
						            		next();
						                }, 2000);
									} else {
										promptus.showErrorMessage(data.message);
										setTimeout(function(){
											promptus.close();
											next();
						                }, 2000);
									}
								},
								error: function(){
									promptus.showErrorMessage("<?php echo $this->translate('Error occured') ?>");
									setTimeout(function(){
										promptus.close();
										next();
						            }, 2000);
								}
							});
						});	
                	},
                	"NO": function(self){
                		setTimeout(function(){
							promptus.close();
							next();
			            });
                	}
                }
			});
		e.preventDefault();
		}
	});
});
// -->
</script>