<script>
window.totalcategories = <?php echo $this->totalcategories?$this->totalcategories:0;?>;
</script>
<form id="frmFilter">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Filter'); ?></h2></td>
          <td>
          	<table>
              <tr>
                <td><?php echo $this->translate('Push Message Name'); ?></td>
                <td><input type="text" class="input" id="txtTemplate" name="pmd[title]"></td>
                <td><?php echo $this->translate('Status'); ?></td>
                 <td>
                	<select name="status">
                		<option value="1"><?php echo $this->translate('Active'); ?></option>
                		<option value="0"><?php echo $this->translate('InActive'); ?></option>
                	</select>
               	</td>
              </tr>
            </table>
          </td>
          <td>&nbsp;</td>
          <td align="right">
          	<input type="submit" name="button" id="button" class="button" value="<?php echo $this->translate('Submit'); ?>">
          </td>
        </tr>
      </table>
</div>
</form>
<a class="togglefilter"></a>
<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
	        <th scope="col"><?php echo $this->translate('Title'); ?></th>
            <th scope="col"><?php echo $this->translate('Category'); ?></th>
	        <th scope="col"><?php echo $this->translate('Description'); ?></th>
            <th scope="col"><?php echo $this->translate('Date/Time'); ?></th>
		    <th scope="col"><?php echo $this->translate('Status'); ?></th>
		    <th scope="col"><?php echo $this->translate('Order'); ?></th>
		    <th scope="col" class="action"><?php echo $this->translate('Action'); ?></th>
		</tr>
    </thead> 
	<tbody>
		<tr>
			<td colspan="3" class="dataTables_empty"><?php echo $this->translate('Loading data from server'); ?></td>
		</tr>
	</tbody>      
</table>

<script type="text/javascript">
var grid ="";
$(document).ready(function() {
	$('a[href="<?php echo $this->addlink;?>"]').on('click',function(e){
		if(!e.isDefaultPrevented()){
			if(window.totalcategories == 0){
				 promptus = new prompt({
	                reference : self,
	                element : ".dataTables_wrapper"
	            });
	            promptus.showErrorMessage("You can not add a push message without category.Please add atleast one category.");
	            setTimeout(function(){
            		promptus.close();
                }, 3000);
				e.preventDefault();
			}
		}
	});
	grid = dataTable({
		aaSorting: [[ 4, "asc" ]],
		"aoColumns": [
						{ "sName": "pmd.title" },
						{ "sName": "pmcd.title" },
						{ "sName": "pmd.description" },
                        { "sName": "pmd.message_date" },
						{ "sName": "pm.status" },
						{ "sName": "pm.order" },						
						{ "sName": "actions","bSortable": false}
					 ],
		id : $('#dataGrid'),
		filterForm : $('#frmFilter'),
		charLimit : [25,25,0,0],
		sAjaxSource: "<?php echo $this->url(array("module"=>"push-message","controller"=>"index","action"=>"grid"));?>"
	});
    $(document).on("submit","#frmFilter",function(){
    	grid.fnDraw();
    	return false;
    });
    
    $(document).on("click",".grid_delete",function(e){
        var self = this;
        window.currentDeleteUrl = $(this).attr("href"); 
        if(!e.isDefaultPrevented()){
        	var promptus = new prompt({
                    	reference : self,
                        element : ".dataTables_wrapper",
                        message : "<?php echo $this->translate('Module will be published automatically. Message will be deleted. Are you ok with it?'); ?>",
                        buttons : {
                            "Yes" : function(self){
                                var prompt = this;
                                $(document).queue(function(next){
                                    prompt.showLoadingMessage("<?php echo $this->translate('Please wait while deleting Message..'); ?>");
                                    next();
                                }).queue(function(next){
                                    $.ajax({
                                        url: window.currentDeleteUrl,
                                        cache: false,
                                        type: "GET",
                                        dataType: "json",
                                        success: function(json){
                                            if(json.success != undefined){ 
                                            	prompt.showSuccessMessage("<?php echo $this->translate('Message deleted successfully.'); ?>");
                                            	setTimeout(function(){
                                            		prompt.close();
                                                	grid.fnDraw();
                                                }, 1000);
                                            } else if(json.errors != undefined){
                                                var errorMessage = "<?php echo $this->translate('Unable to delete Message:'); ?><br />";
                                                errorMessage += json.errors.message;
                                            	prompt.showErrorMessage(errorMessage);
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 2000);
                                            }
                                        },
                                        error: function(){
                                        }
                                    }).complete(next); 
                                });
                            },
                            "No"  : function(self){
                            	this.close();
                            },
                        }
                    });
            e.preventDefault();
        }
    });
    
    $('.togglefilter').on("click",function(){
		$('#filterBox').toggle();
		$(this).toggleClass('flip-vertical');
	});
	$('#filterBox').hide();
});
</script>