<?php 
$generalConfigurationForm = $this->generalConfigurationForm;
$moduleForm = $this->moduleForm;
$data = $this->data;
?>
<style type="text/css">
input[type=button]{ background: none repeat scroll 0 0 lime !important;}
label.dd-option-text,label.dd-selected-text{float:left; width: 200px;line-height:15px !important;padding-top: 15px;}
a.dd-selected:hover{color: black !important;text-decoration: none !important;}
div.iconBox, #background-sel-container{
	border: 1px solid #DCDDE2;
	border-radius: 6px 6px 6px 6px;
	padding: 4px;
	width: 490px;
}
#iconDiv{
	overflow-x: hidden;
	overflow-y: scroll;
	height:85px;
	background-color:black; 
}
#iconDiv div{
	border: 1px solid #DCDDE2;
	display: inline-block;
	width:65px;
	text-align: center;
}
#iconDiv label{
	display:block;
}
#manualDiv{
	padding-bottom: 20px;
}
.float-left{
	float:left;
	padding-left: 14px;
}
#background-sel-container{
	min-height: 127px;
}
#b-image{
	height: 70px;
	padding: 4px 0 5px 0;
}

#b-color{
	height: 40px;
	padding: 10px 0 5px 0;
}
.radio{
	margin-top: 10px;
}
.color-details{
	margin-top: 7px;
}
.image-details{
	margin-top:	31px; 
}
</style>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/colorpicker/jquery.colorpicker.js"); ?>"></script>
<link href="<?php echo $this->baseUrl("libs/colorpicker/jquery.colorpicker.css"); ?>" rel="stylesheet" type="text/css"/>
<script src="<?php echo $this->baseUrl("libs/colorpicker/i18n/jquery.ui.colorpicker-en.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("libs/dropdown/dd.js"); ?>"></script>
<div id="config-tabs">
	<ul>
		<li><a href="#general-config"><?php echo $this->translate('General Configuration');?></a></li>
		<li><a href="#module-config"><?php echo $this->translate('Module Configuration');?></a></li>
		<li><a href="#reorder"><?php echo $this->translate('Reorder');?></a></li>
	</ul>
	<div id="general-config">
		<form action="<?php echo $generalConfigurationForm->getAction(); ?>"
			method="<?php echo $generalConfigurationForm->getMethod();?>"
			id="frmGeneralConfiguration" class="zend_form">
			<?php echo $generalConfigurationForm->customer_configuration_id->renderViewHelper()?>
			<?php echo $generalConfigurationForm->customer_id->renderViewHelper()?>
			<table>
				<tbody>
					<tr>
						<td><?php echo $generalConfigurationForm->font_type->renderLabel() ?></td>
						<td><?php echo $generalConfigurationForm->font_type->renderViewHelper()?></td>
					</tr>
					<tr>
						<td><?php echo $generalConfigurationForm->font_color->renderLabel() ?></td>
						<td><?php echo $generalConfigurationForm->font_color->renderViewHelper()?></td>
					</tr>
					<tr>
						<td><?php echo $generalConfigurationForm->font_size->renderLabel() ?></td>
						<td><?php echo $generalConfigurationForm->font_size->renderViewHelper()?></td>
					</tr>
					<tr>
						<td><?php echo $generalConfigurationForm->spacing->renderLabel() ?></td>
						<td><?php echo $generalConfigurationForm->spacing->renderViewHelper()?></td>
					</tr>
					<tr>
						<td><?php echo $generalConfigurationForm->theme_color->renderLabel(); ?></td>
						<td><?php echo $generalConfigurationForm->theme_color->renderViewHelper()?></td>
					</tr>
				</tbody>
			</table>
			<div class="customer_submit"><?php echo $generalConfigurationForm->submit->renderViewHelper().$generalConfigurationForm->reset->renderViewHelper();?></div>
		</form>
	</div>
	<div id="module-config">
		<div id="data-grid">
			<table style="border-spacing: 0; border-collapse: collapse; width: 100%"
				class="pattern-style-b" id="dataGrid">
				<thead>
					<tr>
						<th scope="col"><?php echo $this->translate('Module Name')?></th>
						<th scope="col"><?php echo $this->translate('Screen Name')?></th>
						<th scope="col"><?php echo $this->translate('Visible')?></th>
						<th scope="col"><?php echo $this->translate('Order')?></th>
						<th scope="col"><?php echo $this->translate('Published')?></th>
						<th scope="col" class="action"><?php echo $this->translate('Actions')?></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td colspan="6" class="dataTables_empty"><?php echo $this->translate('Loading data from server')?></td>
					</tr>
				</tbody>
			</table>
		</div>
		
		<div id="data-form" style="display: none;">
			<form action="<?php echo $moduleForm->getAction(); ?>"
				method="<?php echo $moduleForm->getMethod();?>"
				id="frmModuleConfiguration" class="zend_form">
				<?php echo $moduleForm->customer_module_id->renderViewHelper()?>
				<?php echo $moduleForm->language_id->renderViewHelper()?>
				<table>
					<tbody>
						<tr>
							<td><?php echo $moduleForm->screen_name->renderLabel() ?></td>
							<td><?php echo $moduleForm->screen_name->renderViewHelper()?></td>
						</tr>
						<tr>
							<td valign="top">
								<label for="icon"><?php echo $this->translate('Icon:'); ?></label> 
							</td>
							<td valign="top">
								<div class="iconBox" id="iconDiv">
								</div>
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>
					        	<div class="iconBox" id="manualDiv">
					        		<input type="radio" checked='checked' name="selIcon" id="selIcon_0" value=0>
						        	<label for=icon>Default:</label>
						        	<input id="icon" type="file" name="icon" disabled="disabled"/>
						        	<input id="icon_path" type="hidden" name="icon_path" />
						        	(Size: 120px &#215; 120px )
									<img alt="" id="img-icon" height=60 width=60 />
								</div>
							</td>
						</tr>
						<tr>
							<td><label for="background_image"><?php echo $this->translate('Background Image:'); ?></label> </td>
					        <td>
					        	<input type="hidden" name="background_type" value="1">
					        	<div id="background-sel-container">
						        	<div class="float-left" id="b-image">
							        	<div class="float-left image-details"> 
							        		<input type="radio" id="sel-image" name="sel-background" value="1">
							        	</div>
							        	<div class="float-left image-details">
							        		<span>Image:</span>
							        	</div>
							        	<div class="float-left">
							        		<div id="myDropdown"></div>
							        	<input id="background_image" type="hidden" name="background_image" />
							        	</div>
							        </div>
						        	<div class="float-left" id="b-color">
							        	<div class="float-left color-details">
							        		<input type="radio" name="sel-background" id="sel-color" value="0">
							        	</div>
							        	<div class="float-left color-details">
							        		<span>Color:</span>
							        	</div>
							        	<div class="float-left">
											<input name="background_color" id="background_color" type="text" value="000000">
										</div>
									</div>
								</div>
							</td>
						</tr>
						<tr>
							<td><?php echo $moduleForm->visibility->renderLabel() ?></td>
							<td><?php echo $moduleForm->visibility->renderViewHelper()?></td>
						</tr>
					</tbody>
				</table>
				<div class="customer_submit"><?php echo $moduleForm->submit->renderViewHelper().$moduleForm->applyall->renderViewHelper().$moduleForm->cancel->renderViewHelper();?></div>
			</form>
		</div>
	</div>
	<div id="reorder">
			<form id="frmFilter">
			<div id="filterBox">
			      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
			        <tr>
			          <td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Reorder Modules'); ?></h2></td>
			          <td align="right">
			          	<input type="submit" name="button" id="save-order" class="button" value="<?php echo $this->translate('Save')?>" />
			          	<input type="reset" name="reset" id="reorder-reset" class="button" value="<?php echo $this->translate('Reset')?>" />
			          </td>
			        </tr>
			      </table>
			</div>
			</form>
			<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGridReorder">
				<thead>
					<tr>
						<th scope="col"><?php echo $this->translate('Module Name'); ?></th>
					    <th scope="col"><?php echo $this->translate('Visible'); ?></th>
					 	<th scope="col"><?php echo $this->translate('Published'); ?></th>
					</tr>
			    </thead> 
				<tbody>
				<?php 
					foreach($data as $row) {
				?>
				<tr id="index-<?php echo $row["cm.customer_module_id"];?>" class="sortable" style="cursor: move;">
					<td><?php echo $row['m.name']; ?></td>
				   	<td><?php echo ($row['cm.visibility']==1)? "YES" : "NO"; ?></td>
				   	<td><?php echo $row['cm.is_publish']; ?></td>
				</tr>
				<?php } ?>
				</tbody>      
			</table>
	</div>
</div>
<script type="text/javascript">
var grid ="";
	$(document).ready(function(){
		$("#font_color,#theme_color").colorpicker({
			parts: 'draggable',
			showOn: 'both',
			regional: 'en',
			buttonColorize: true,
			showNoneButton: false,
			alpha: true,
			close : function(){
				//$(this).val("#"+$(this).val());
				var self = $(this);
				$(this).parent().find("button").css({background:"#"+self.val()});
			}
		});
		//$(":button").css('background',"none");
	document.onselectstart = function() {return false;}
		$( "#config-tabs" ).tabs();
		$("#frmGeneralConfiguration").validator().submit(function(e){
			if(!e.isDefaultPrevented()){
				var self = this;
				var promptus = false;
				$(document).queue(function(next){
					promptus = new prompt({
						element : $("#config-tabs"),
						reference : self,
						beforeShow : function(){
							this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Configuration..');?>");
						}
					});
					next();
				}).queue(function(next){
					$.ajax({
						url : "<?php echo $this->url(array("module"=>"default","controller"=>"configuration","action"=>"save-general-configuration"),"default",true);?>",
						cache : false,
						type : "POST",
						data : $(self).serialize(),
						dataType : "json",
						success : function(json){
							if( json && json.success != undefined ) {
								var customer_configuration = json.success.message;
								$(self).find("#customer_configuration_id").attr("value",customer_configuration.customer_configuration_id);								
								promptus.showSuccessMessage("<?php echo $this->translate('Configuration saved successfully');?>");
								setTimeout(function(){
									next();
								}, 2000);
							} else if( json && json.errors != undefined ){
								if( typeof(json.errors.message) == "string"){
										promptus.showErrorMessage(json.errors.message);
										setTimeout(function(){
											next();
										}, 2000);
								} else {
									$(self).data("validator").invalidate(json.errors);
									next();
								}
							}
						},
						error : next
					});
				}).queue(function(next){
					promptus.close();
					next();
				});
			}
			e.preventDefault();
		});

		grid = dataTable({
			aaSorting: [[ 3, "desc" ]],
			"aoColumns": [
							{ "sName": "m_description" },
							{ "sName": "d_screen_name" },
							{ "sName": "cm_visibility" },
							{ "sName": "cm_order_number" },
							{ "sName": "cm_is_publish" },
							{ "sName": "actions","bSortable": false}
						 ],
			id : $('#dataGrid'),
			filterForm : null,
			charLimit : [20,20,0,0,0],
			sAjaxSource: "<?php echo $this->url(array("module"=>"default","controller"=>"configuration","action"=>"grid"));?>"
		});
		$(document).on("click",".grid_publish",function(e){
	        var self = this; 
			window.currentModulePublishUrl = $(this).attr("href"); 
	        if(!e.isDefaultPrevented()){
	        	var promtus = new prompt({
	            	reference : self,
	                element : "#config-tabs",
	                message : "<?php echo $this->translate('Are you sure you want to publish this Module?')?>",
	                buttons : {
	                    "Yes" : function(self){
	                        var prompt = this;
	                        $(document).queue(function(next){
	                            prompt.showLoadingMessage("<?php echo $this->translate('Please wait while publishing module...')?>");
	                            next();
	                        }).queue(function(next){
	                        	$.ajax({
	                                url: window.currentModulePublishUrl,
	                                cache: false,
	                                type: "GET",
	                                dataType: "json",
	                                success: function(json){
	                                    if(json.success != undefined){ 
	                                    	prompt.showSuccessMessage("<?php echo $this->translate('Module pubished successfully.')?>");
	                                    	setTimeout(function(){
	                                    		prompt.close();
	                                        	grid.fnDraw();
	                                        }, 1000);
	                                    } else if(json.errors != undefined){
	                                        var errorMessage = "<?php echo $this->translate('Unable to publish module error returned:')?><br />";
	                                        errorMessage += json.errors;
	                                    	prompt.showErrorMessage(errorMessage);
	                                    	setTimeout(function(){
	                                    		prompt.close();
	                                        }, 2000);
	                                    }
	                                },
	                                error: function(){
	                                }
	                            }).complete(next); 
	                        });
	                    },
	                    "No"  : function(self){
	                    	this.close();
	                    },
	                }
	            });
	            e.preventDefault();
	        }
	    });

		$(document).on("click",".edit",function(e){
	        var self = this; 
			window.currentEditUrl = $(this).attr("href"); 
	        if(!e.isDefaultPrevented()){
		        var promptus = new prompt({
			        	reference : self,
		                element : "#config-tabs",
			        });
	        	$(document).queue(function(next){
	        		$('#frmModuleConfiguration').each (function(){
	        			  this.reset();
	        		});
	        		promptus.showLoadingMessage("<?php echo $this->translate('Please wait...')?>");
                    next();
                }).queue(function(next){
	        		$.ajax({
                    	url: window.currentEditUrl,
                        cache: false,
                        type: "GET",	
                        dataType: "json",
                        success: function(json){
                        	if(json.success != undefined){ 
                            	// Success Show Record To Edit.
                            	data = json.success;
								dropdown = json.dropdown;								
								icons = json.icons;
								selectedIcon = icons.selected;
									$("#iconDiv").html("") ;
									$.each(icons.icons, function(i,icon) {
										var checked = "";
									if(selectedIcon == icon){
										checked = "checked='checked'";
									}	
									  $("#iconDiv").append(
										"<div>"+
											"<label for=icon_"+i+"><img src="+
											"<?php echo $this->baseUrl('/resource/default/images/icon/') ?>"+icon+
											" height=60 width=60>"+
											"</label>"+
											"<input type=radio "+checked+" name=selIcon id=icon_"+i+" value="+icon+">"+
										"</div>"
										);
									});
                            	$("#customer_module_id").attr("value",data["cm_customer_module_id"]);
                            	$("#language_id").attr("value",data["d_language_id"]);
                            	$("#icon_path").attr("value",data["cm_icon"]);
                            	$("#screen_name").attr("value",data["d_screen_name"]);
                            	if(data["d_background_color"] != ""){
                            		$("#background_color").attr("value",data["d_background_color"]);
                            	}else{
                            		$("#background_color").attr("value",'');
                            	}                           	
                            	//$('#background_color').trigger('keyup');
                            	$('#myDropdown').ddslick('destroy'); 
                            	$('#myDropdown').ddslick({
                                	data:dropdown,
                        			width:300,                      			
                        		    selectText: "Select your preferred background image",
                        		    imagePosition:"left",   
                        		});
                            	$('#myDropdown').on("click",function(){
                        			var data = $('#myDropdown').data('ddslick');
                        			var id = data.selectedData.value;
                        			$("#background_image").attr("value",id);
                            	});
                            	if(data["cm_icon"] != ""){
                            		$("#img-icon").attr("src","<?php echo $this->baseUrl()."/resource/default/images/icon/"; ?>" + data["cm_icon"]);
                            	}
                            	if(data["d_background_type"]==0){
                            		$("#sel-color").attr("checked","checked");
                            		$("input[name=background_type]").attr("value","0");	
                            	}else{
                            		$("#sel-image").attr("checked","checked");
                            		$("input[name=background_type]").attr("value","1");
                            		$("input[id=background_color]").attr("disabled","disabled");
                            	}
                            	if(data["cm_visibility"]==1) {
                            		$("#visibility").attr("checked","checked");
                            	} else {
                            		$("#visibility").removeAttr("checked");
                            	}
                            	$("input[name=sel-background]").on("change",function(){
                            		if($(this).attr("id") == "sel-image"){
                            			$("input[name=background_type]").attr("value","1");
                            			$("input[id=background_color]").attr("disabled","disabled");
                            		}else{
                            			$("input[name=background_type]").attr("value","0");
                            			$("input[id=background_color]").removeAttr("disabled","disabled");
                            		}
                            	});
                            	$("#data-grid").hide();
                            	$("#data-form").show();
                            	$("#background_color").colorpicker({
									parts: 'draggable',
									showOn: 'both',
									regional: 'en',
									buttonColorize: true,
									showNoneButton: false,
									alpha: true,
									altOnChange: true ,
									close : function(){
										//$(this).val("#"+$(this).val());
										var self = $(this);
										$(this).parent().find("button").css({background:"#"+self.val()});
									},
									init: function() {
										window.colorbutton = $(this);
									}
								});
								
								window.colorbutton.parent().find("button").css({
									background:"#"+window.colorbutton.val()
								});
								window.colorbutton.parent().find("img").css({
									background:"#"+window.colorbutton.val()
								});
								/*window.colorbutton.close();*/
	                            setTimeout(function(){
	                            	promptus.close();
	                            }, 1000);
                            } else if(json.errors != undefined){
	                        	var errorMessage = "<?php echo $this->translate('Unable to edit module error returned:')?><br />";
	                            errorMessage += json.errors;
	                            promptus.showErrorMessage(errorMessage);
	                            setTimeout(function(){
	                            	promptus.close();
	                            }, 2000);
	                        }
                       	}
                	}).complete(next);
                }).queue(function(next){
                	promptus.close();
                    next();
            	});
	      		e.preventDefault();
	    	}
	    });
		$("#applyall").on("click",function(e){
			if(!e.isDefaultPrevented()){
		    	var promptus = new prompt({
		            	reference :"#frmModuleConfiguration",
		                element : $("#config-tabs"),
		                message : "<?php echo $this->translate('Your changes will be saved and applied to all languages. Is it Ok?'); ?>",
		                buttons : {
		                    "Yes" : function(self){
		                        $("#frmModuleConfiguration").trigger("submit",{all:true});
		                    },
		                    "No"  : function(self){
		                    	this.close();
		                    },
		                }
		            });
		        e.preventDefault();
		    }
		});
		$("#frmModuleConfiguration").validator().submit(function(e,customObject){
			customObject = customObject || {};
			var queryAppend = "";
			if(customObject.all){
				queryAppend = "&all=true";
			}
			if($("input[name=background_type]").val() == 0){
				$("#background_image").attr("value","");
			}else{
				$("#background_color").attr("value","");
			}	
			if(!e.isDefaultPrevented()){
				var self = this;
				var promptus = false;
				$(document).queue(function(next){
					promptus = new prompt({
						element : $("#config-tabs"),
						reference : self,
						beforeShow : function(){
							this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Module Configuration..');?>");
						}
					});
					next();
				}).queue(function(next){
					// Upoad Images
					$("input[type='file']").each(function(){
						var input = $(this).attr("id");
						if($(this).attr("value") != "")
						{
							$.ajaxFileUpload({
								url:'<?php echo $this->url(array("module"=>"default","controller"=>"configuration","action"=>"upload"),"default",true);?>',
								secureuri:false,
								fileElementId:$(this).attr("id"),
								dataType: 'json',
								data:{upload:$(this).attr("id")},
								success: function (data, status)
								{
									if(data.success != undefined) {
										$("#"+ input + "_path").attr("value",data.success);
									}	
								},
								complete: function(){
									next();
								}
							});
						} else {
							next();
						}
					});
				}).queue(function(next){
					// Save Modules
					$.ajax({
						type : "POST",
						cache : false,
						data : $(self).serialize() + queryAppend,
						dataType: 'json',
						url : "<?php echo $this->url(array("module"=>"default","controller"=>"configuration","action"=>"save-module"),"default",true);?>",
						success : function(json){
							if(json.errors != undefined){
								promptus.showErrorMessage(json.errors);
								next();
							} else if(json.success != undefined){
								promptus.showSuccessMessage("<?php echo $this->translate('Module updated successfully.'); ?>");
								setTimeout(function(){
									grid.fnDraw();
									hideForm();
									next();
								}, 2000);
							}
						},
						complete: function(){
							next();
						}
		  			});
				}).queue(function(next){
					promptus.close();
					next();
				});
			}
			e.preventDefault();
		});
	});
	window.dragStartIndex = 0;
	//  $(".sortable:eq(1)").insertBefore($(".sortable:eq(0)"));
	$(".sortable").on("mousedown",function(){
		window.dragStartIndex = $(this).index(".sortable") + 1;
		$(this).addClass("drag-start");
	});
	$(".sortable").on("mouseover",function(){
		if(window.dragStartIndex>0 && window.dragStartIndex != ($(this).index(".sortable") + 1)) {
			var fromIndex = window.dragStartIndex - 1;
			var toIndex = $(this).index(".sortable");
			if(fromIndex > toIndex) {
				$(".sortable:eq("+fromIndex+")").insertBefore($(".sortable:eq("+toIndex+")"));
			} else {
				$(".sortable:eq("+fromIndex+")").insertAfter($(".sortable:eq("+toIndex+")"));
			}
			window.dragStartIndex = toIndex+1;
		}
	});
	$(document).on("mouseup",function(){window.dragStartIndex = 0; $(".sortable").removeClass("drag-start");});
	$("#dataGridReorder").on("mousedown",function(){return false;});
	$(document).on("click","#save-order",function(e){
        var self = this;
        window.currentDeleteUrl = location.href; 
        if(!e.isDefaultPrevented()){
        	var promptus = new prompt({
                    	reference : self,
                        element : "#content",
                        message : "<?php echo $this->translate('Are you sure you want to save website order?'); ?>",
                        buttons : {
                            "Yes" : function(self){
                                var prompt = this;
                                $(document).queue(function(next){
                                    prompt.showLoadingMessage("<?php echo $this->translate('Please wait while saving website order..'); ?>");
                                    next();
                                }).queue(function(next){
                                    $.ajax({
                                        url: "<?php echo $this->url(array("module"=>"default","controller"=>"configuration","action"=>"reorder"),"default",true);?>",
                                        cache: false,
                                        type: "POST",
                                        dataType: "json",
                                        data: serializeOrder(),
                                        success: function(json){
                                            if(json.success != undefined){ 
                                            	prompt.showSuccessMessage("<?php echo $this->translate('website reordered successfully.'); ?>");
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 1000);
                                                location.href = location.href;
                                            } else if(json.errors != undefined){
                                                var errorMessage = "<?php echo $this->translate('Unable to reorder website:'); ?><br />";
                                                errorMessage += json.errors.message;
                                            	prompt.showErrorMessage(errorMessage);
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 2000);
                                            }
                                        },
                                        error: function(){
                                        }
                                    }).complete(next); 
                                });
                            },
                            "No"  : function(self){
                            	this.close();
                            },
                        }
                    });
            e.preventDefault();
        }
    });
	$("#reorder-reset").on("click", function(){
		location.href = location.href;
	});
	function serializeOrder(){
		var response = {order:{}};
		$(".sortable").each(function(){
			var index = ($(this).attr("id") + "").replace("index-","");
			response["order"][$(this).index(".sortable")+1] = index;
		});
		return response;
	}
	function hideForm() {
		$("#data-grid").show();
    	$("#data-form").hide();
	}
	$(document).on("change","input:radio[name=selIcon]",function(){
		if($('input:radio[name=selIcon]:checked').val() == 0)
		{
			$("#icon").removeAttr("disabled");
		} else {
			$("#icon").attr("disabled","disabled");
		}			
	});	
</script>