<style type="text/css">
div.logo-box {
	width: auto;
	margin: 10px 0;
	padding: 10px 15px;
}
.image-container {
	float:left;
	border: 1px solid #DCDDE2;
	width: 265px;
	margin:5px 0 10px 9px; 
	padding: 10px;
}
.image-container:hover {
	box-shadow:1px 1px 5px rgba(0, 0, 200, 0.20);
}
.thumb {
	text-align: center;
}
.thumb .label{
	float: left;
}
</style>
<div id="filterBox">
	<table
		style="width: 100%; border: 0; border-spacing: 0; border-collapse: collapse;">
		<tr>
			<td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Bulk Upload');?></h2></td>
		</tr>
	</table>
</div>
<div class="boxBorderBottom">
<form id="frmBulkUpload" method="post" name="frmBulkUpload">
	<div class="logo-box">
		<label for="category">Category:</label>
		<select id="category" name="category">
			<?php foreach($this->categories as $key => $category) { ?>
				<option value="<?php echo $key; ?>"><?php echo $category; ?></option>
			<?php } ?>
		</select>
		<label for="image">Select Image: </label>
		<input id="image" type="file" multiple="multiple" name="image[]" />
		<input type="submit" name="button" id="button" class="button" value="<?php echo $this->translate('Upload'); ?>" />
		<input type="submit" name="btnSave" disabled="disabled" id="btnSave" class="button" value="<?php echo $this->translate('Save'); ?>" />
	</div>
	<div id="divImages" class="logo-box" style="min-height: 400px;">
	</div>
</form>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$("#button").on("click",function(e){
		var promptus = false;
		if(!e.isDefaultPrevented()){
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : $("#content"),
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Images..')?>");
	                }
	            });
	            next();
			}).queue(function(next){
				if($("#category").attr("value") == "")
	            {
	            	promptus.showErrorMessage("Please select category");
					setTimeout(function(){
						promptus.close();
						next();
					}, 2000);
					return false;
	            } else if($("#image").attr("value") == "") {
	            	promptus.showErrorMessage("Please select images to upload");
					setTimeout(function(){
						promptus.close();
						next();
					}, 2000);
					return false;
	            }
				$.ajaxFileUpload({	
					url: location.href,
					secureuri: false,
					fileElementId: "image",
					dataType: 'json',
					async : false,
					data:{upload:'true',category_id:$("#category").attr("value")},
					success: function (data, status) {
						if(data.success != undefined) {
							$.each(data.result,function(i,item) {
								var html = '<div class="image-container">';
								html += '<div class="thumb">';
								html += '<img src="'+item.image_path+'" alt="" width=240 height=200 />';
								html += '<input type="hidden" value="'+item.module_image_gallery_id+'" name="module_image_gallery_id[]" />';
								html += '</div>';
								html += '<div class="details">';
								html += '<table width="100%" border="0">';
								html += '<tr><td><label class="label">Title: </label></td><td><input type="text" id="title_'+item.module_image_gallery_id+'" name="title_'+item.module_image_gallery_id+'" /></td></tr>';
								html += '<tr><td><label class="label">Description: </label></td><td><textarea id="description_'+item.module_image_gallery_id+'" name="description_'+item.module_image_gallery_id+'"></textarea></td></tr>';
								//html += '<tr><td colspan="2"><input type="button" class="button" value="Apply To All" onclick="applyToAll("'+item.module_image_gallery_id+'");" /></td></tr>';
								html += '</table>';
								html += '</div>';
								html += '</div>';
								
								$("#divImages").append(html);
								$("#button").attr("disabled","disabled");
								$("#btnSave").removeAttr("disabled");
							});
							$("#divImages").append('<div class="clear"></div>');
						}
						promptus.close();
					},
					error: function (data, status, e) {
						promptus.showErrorMessage("<?php echo $this->translate('Error uploading Images.')?>");
						setTimeout(function(){
							promptus.close();
						}, 2000);
						return false;
					},
					complete: function(){
						next();
					}
				});
			});
			e.preventDefault();
		}
	});
	$("#btnSave").on("click",function(e){
		// Save Images
		var form = $("#frmBulkUpload");
		var promptus = false;
		if(!e.isDefaultPrevented()){
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : $("#content"),
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Image details..')?>");
	                }
	            });
	            next();
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize(),
					url : location.href,
					dataType : "json",
					success : function(json){
						if(json.errors != undefined){
							promptus.showErrorMessage("<?php echo $this->translate('Error saving images details.')?>");
							next();
						} else if(json.success != undefined){
							promptus.showSuccessMessage("<?php echo $this->translate('Image details saved successfully.')?>");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"module-image-gallery","controller"=>"index","action" => "index"),"default",true);?>";
								next();
							}, 2000);
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
			});
			e.preventDefault();
		}
	});
});
</script>