<?php
$class = 'class="first"';
$i = 0;
echo '<ul id="menu-bar">';
foreach ( $this->container as $index => $page ) {
	if($page->isVisible() && $this->navigation()->getAcl()->isAllowed($this->navigation()->getRole(),$page->getResource())) {
		echo '<li>';
		$class = "";
		echo '<a href="' . $page->getHref () . '" ' . $class . '>' . $this->translate($page->getLabel ()) . '</a>';
		
		$submenu = "";
		foreach($page->pages as $subPage) {
			if($subPage->isVisible() && $this->navigation()->getAcl()->isAllowed($this->navigation()->getRole(),$subPage->getResource())) {
				$submenu .= '<li>';
				$submenu .= '<a href="' . $subPage->getHref () . '">' . $this->translate($subPage->getLabel ()) . '</a>';
				$submenu .= "</li>";
			}
		}
		if($submenu != "") {
			echo "<ul>". $submenu ."</ul>";
		}
		echo "</li>";
	}
}
echo "</ul>";
?>