<?php $form = $this->form; ?>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxcore.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/gettheme.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxdropdownbutton.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxscrollbar.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxbuttons.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxtree.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxpanel.js"); ?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl("libs/innovaeditor/scripts/innovaeditor.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/innovaeditor/scripts/jquery.innovaeditor.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/innovaeditor/scripts/editor.aksPlugin.js"); ?>"></script>

<style>
.popupLabel{
	display:inline;
	display:inline-block;
	width: 50px;
	padding: 5px;
}

.popupInput{
	display:inline;
	display:inline-block;
	padding: 5px;
}
.popupSubmit{
	margin-left: 115px;
	margin-top: 5px;
}
.textareaContent *{
	vertical-align: top;
	resize:none;
	margin-top: 3px;
}

div.textareaContent textarea{
	margin-left: 20px;
	width:410px;
	height: 45px;
}

.locationLabel{
	display:inline;
	display:inline-block;
	width: 50px;
	padding: 5px;	
}

.locationInput{
	display:inline;
	display:inline-block;
	padding: 5px;	
}

#load-locations{
	display: none;
}

#gMap {
	margin: auto;
	border: 1px solid #DCDDE2;
	width: 100%;
	height: 190px;
}
.singleEntry{
	display: block;
	clear: both;
	padding: 20px 0px 0px 244px;
}
</style>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/mustache/mustache.js") ?>"></script><div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
          <td align="right"><h2><?php echo $this->language; ?></h2></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditEvent" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php echo $form->module_events_id->renderViewHelper(); ?>
	<?php echo $form->module_events_category_id->renderViewHelper(); ?>
	<?php echo $form->module_events_detail_id->renderViewHelper(); ?>
	<?php echo $form->language_id->renderViewHelper(); ?>
	<table style="margin:10px 0;">
		<tbody>
			<tr>
				<td><label for="tree"><?php echo $this->translate('Select Category:'); ?></label></td>
				<td>
					<div id='jqxWidget'>
						<div id="dropDownButton">
							<div id='jqxTree'></div>
						</div>
					</div>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->module_events_types_id->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->module_events_types_id->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->title->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->title->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->start_date_time->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->start_date_time->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->end_date_time->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->end_date_time->renderViewHelper()?>
				</td>
			</tr>
			<tr>
    			<td valign="top">
    					<label><?php echo $this->translate('Icon:')?></label>
    			</td>
    			<td valign="top">
    				<div id="lstLogo" class="logo-box">
        				<?php $resource_path = $this->baseUrl("resource/events/preset-icons");?>
        				<?php foreach ($this->iconpack as $icon):?>
        				<div class="">
    						<label for="selLogo_<?php echo $icon; ?>">
    							<img src="<?php echo $resource_path . "/" . $icon; ?>" width="64" />
    						</label>
    						<input type="radio" id="selLogo_<?php echo $icon; ?>" name="selLogo" value="<?php echo $icon; ?>" />
    					</div>
        				<?php endforeach;?>
    				</div>
    			</td>
			</tr>
			
			<tr>
		        <td>&nbsp;</td>
			    <td>
		        	<div class="logo-box">
		        		<table>
    						<tr>
    							<td>
    								<?php 
    								$icon_path = $this->baseUrl("resource/events/");
    					        	if($this->icon_src!="") {
    					        	?>
    					        	<img class="iconImage" alt="" src="<?php echo $icon_path."/".$this->icon_src;?>" style="width: 64px;" />
    					        	<?php 
    					        	}
    					        	?>
    				        	</td>
    				        	<td>
    				        		<?php
    				        		$checked = "";
    					        	if($this->icon_src!="") {
    					        		$checked = "checked='checked'";
    								}
    								?>
    					        	
    								<input type="radio" id="selLogo_0" checked="checked" name="selLogo" value="0" style="margin-left: 10px;" />
    								<label for="selLogo_0"><?php echo $this->translate('Upload:')?></label>
    								<input id="icon" type="file" name="icon" /> (Size: 60px &#215; 60px )
    					        	<input id="icon_path" type="hidden" name="icon_path" value="" />
    				        	</td>
    			        	</tr>
			        	    <tr id="deleteIconButton">
    			        	 <?php if($this->icon_src!=""){ ?>
    						    <td>
    							    <div class="deletebuttons"><a class="deleteIcon red button-grid">Delete</a></div>
    						    </td>
    					    </tr>
					        <?php } ?>
			        	</table>
					</div>
				</td>
			</tr>
			<!--  
			<tr>
		    	<td><label for="image"><?php echo $this->translate('Image:')?></label> </td>
		        <td>
		        	<input id="image" type="file" name="image" />
		        	<input id="image_path" type="hidden" name="image_path" value="<?php echo $this->image_path; ?>" />
		        	(Size: 120px &#215; 120px )
		        	<img alt="" src="<?php echo $this->image_src;?>" style="max-width: 120px;" />
				</td>
			</tr>
			-->
			<tr>
		        <td><label for="image"><?php echo $this->translate('Image:')?></label></td>
			    <td>
		        	<div class="logo-box">
		        		<table>
    						<tr>
    							<td>
    								<?php 
    								$icon_path = $this->baseUrl("resource/events/");
    					        	if($this->image_src!="") {
    					        	?>
    					        	<img class="iconImage" alt="" src="<?php echo $this->image_src;?>" style="width: 64px;" />
    					        	<?php 
    					        	}
    					        	?>
    				        	</td>
    				        	<td>
    								<input id="image" type="file" name="image" /> (Size: 60px &#215; 60px )
    					        	<input id="image_path" type="hidden" name="image_path" value="" />
    				        	</td>
    			        	</tr>
			        	    <tr id="deleteIconButton">
    			        	 <?php if($this->icon_src!=""){ ?>
    						    <td>
    							    <div class="deletebuttons"><a class="deleteIcon red button-grid">Delete</a></div>
    						    </td>
    					    </tr>
					        <?php } ?>
			        	</table>
					</div>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->description->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->description->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->information->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->information->renderViewHelper()?>
				</td>
			</tr>
			<tr>
				<td>
					<label>Event Location(s):</label>
				</td>
				<td>
					<div id="mainContainer">
						<div class="footer" style="clear:both">
							<a class="button-grid greay addEventLocation">Add Location</a>
							<a class="button-grid greay loadEventLocation">Get Location</a>
						</div>
						<div id="locationContainer">
						</div>
					</div>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->notes->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->notes->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->phone->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->phone->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->email->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->email->renderViewHelper()?>
				</td>
			</tr>
			<tr>
				<td><?php echo $form->website->renderLabel() ?></td>
				<td><?php echo $form->website->renderViewHelper() ?></td>
			</tr>
			<tr>
		    	<td><?php echo $form->code->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->code->renderViewHelper()?>
				</td>
			</tr>
			<!--<tr>
		    	<td><?php //echo $form->recurrence->renderLabel() ?></td>
		        <td>
		        	<?php //echo $form->recurrence->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php //echo $form->stop_by->renderLabel() ?></td>
		        <td>
		        	<?php //echo $form->stop_by->renderViewHelper()?>
		        	<?php //echo $form->stop_at->renderViewHelper()?>
		        	<div id="divOcurrence" style="display:inline;">
		        		<input id="stop_at_ocurrence" name="stop_at_occurence" value="1" />
		        	</div>
		        	<div id="divDate" style="display: none;">
		        		<input id="stop_at_date" name="stop_at_date" value=""  />
		        	</div>
				</td>
			</tr> -->
			<tr>
		    	<td><label>Push Message:</label></td>
		        <td><input type="checkbox" name="sendpush" id="sendpush" /></td>
			</tr>
			<tr>
		    	<td><?php echo $form->status->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->status->renderViewHelper()?>
				</td>
			</tr>			
			<tr>
		        <td colspan="3" align="center">
		        	<?php echo html_entity_decode($form->submit->renderViewHelper()) ?>&nbsp;
		        	<?php echo (Standard_Functions::$action == "edit")? html_entity_decode($form->applyall->renderViewHelper()):""?>&nbsp;
					<?php echo html_entity_decode($form->reset->renderViewHelper()) ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<div id="hiddenPopup" style="display:none">
	<div id="gMap">&nbsp;</div>
	<div>
		<input type="checkbox" checked="checked" name="mark-fixed" id="mark-fixed" />
		<label for="mark-fixed"><?php echo $this->translate('Auto Locate')?> </label>
	</div>
</div>
<script type="text/template" id="locationTemplate">
	<div class="locationBox" id="record-{{id}}">
		<div style="float:left">
			<div class="locationLabel">
				<?php echo $form->location->renderLabel() ;?>
			</div>
			<div class="locationInput">
				<?php echo $form->location->renderViewHelper() ;?>
			</div>
		</div>
		<div>
			<div class="locationLabel">
				<?php echo $form->plz->renderLabel() ;?>
			</div>
			<div class="locationInput">
				<?php echo $form->plz->renderViewHelper() ;?>
			</div>
		</div>
		<div class="deleteLocation delete-{{id}}">
			<a class='deleteLink'>Delete</a>
		</div>
		<div style="float:left">
			<div class="locationLabel">
				<?php echo $form->country->renderLabel() ;?>
			</div>
			<div class="locationInput">
				<?php echo $form->country->renderViewHelper() ;?>
			</div>
		</div>
		<div>
			<div class="locationLabel">
				<?php echo $form->latitude->renderLabel() ;?>
			</div>
			<div class="locationInput">
				<?php echo $form->latitude->renderViewHelper() ;?>
			</div>
		</div>
		<div style="float:left">
			<div class="locationLabel"> 
				<?php echo $form->city->renderLabel() ;?>
			</div>
			<div class="locationInput">
				<?php echo $form->city->renderViewHelper() ;?>
			</div>
		</div>
		<div>
			<div class="locationLabel">
				<?php echo $form->longitude->renderLabel() ;?>
			</div>
			<div class="locationInput">
				<?php echo $form->longitude->renderViewHelper() ;?>
			</div>
		</div>

		<div class="textareaContent" style="float:left">
			<?php echo $form->address->renderLabel() ;?>
			<?php echo $form->address->renderViewHelper() ;?>
		</div>
		<div class="hrRepeat" style="clear:both; padding: 16px 0px"><hr class="eventHrStyle"></div>
	</div>
</script>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$('#information').editor({
		width:650,
        height: 600,
        innerWidth:320,
        enableFlickr: true,
        css: ['<?php echo $this->baseUrl("libs/innovaeditor/styles/default.css");?>'] ,
        groups: [
                ["group1", "", ["FontName", "FontSize", "Superscript", "ForeColor", "BackColor", "FontDialog", "Styles", "BRK", "Bold", "Italic", "Underline", "Strikethrough", "TextDialog","CompleteTextDialog", "RemoveFormat"]],
		        ["group2", "", ["JustifyLeft", "JustifyCenter", "JustifyRight", "Paragraph", "BRK", "Bullets", "Numbering", "Indent", "Outdent"]],
		        ["group3", "", ["Table","TableDialog", "Emoticons", "FlashDialog", "BRK", "LinkDialog", "ImageDialog", "YoutubeDialog"]],
		        ["group4", "", ["InternalLink", "Undo", "Redo", "Line", "BRK", "SearchDialog", "CharsDialog", "SourceDialog", "FullScreen"]]
                ],
        fileBrowser:['<?php echo $this->baseUrl("libs/innovaeditor/assetmanager/asset.php");?>']
    });
	var queryAppend = "";
	var parentIdLabel = "<?php echo $this->parentCategory; ?>";
	var data = <?php echo $this->categoryTree; ?>;
	var builddata = function () {
		var source = [];
	    var items = [];
	    items[0]={id:0,label:'Root',selected:false};
		source[0] = items[0];
	    for (var i = 0; i < data.length; i++) {
	        var item = data[i];
	        var label = item["text"];
	        var parentid = item["parentId"];
	        var id = item["id"];

	        if (items[parentid]) {
	            var item = { id: id, label: label, item: item };
	            if (!items[parentid].items) {
	                items[parentid].items = [];
	            }
	            items[parentid].items[items[parentid].items.length] = item;
	            items[id] = item;
	        }
	        else {
	            items[id] = { id: id, label: label, item: item };
	            source[id] = items[id];
	        }
	    }
	    return source;
	};
	$(".deleteIcon").on("click",function(){
    	$("#icon_path").attr("value","deleted");
    	$(".iconImage").remove();
    	$("#icon").attr("value","");
    	$("tr#deleteIconButton").remove();
    });
	$("#dropDownButton").jqxDropDownButton({ width: 150, height: 25 });
	$('#jqxTree').bind('initialized', function (event) { 
		var args = event.args;
		parentIdLabel = (parentIdLabel=="")?"Root":parentIdLabel;
    	var dropDownContent = '<div style="position: relative; margin-left: 3px; margin-top: 5px;">' + parentIdLabel + '</div>';
    	$("#dropDownButton").jqxDropDownButton('setContent', dropDownContent);
    });	
	$('#jqxTree').bind('select', function (event) {
        var args = event.args;
        var item = $('#jqxTree').jqxTree('getItem', args.element);
        $("#module_events_category_id").attr("value",item.id);
        var dropDownContent = '<div style="position: relative; margin-left: 3px; margin-top: 5px;">' + item.label + '</div>';
        $("#dropDownButton").jqxDropDownButton('setContent', dropDownContent);
    });
	$('#jqxTree').bind('click', function (event) {
		$("#dropDownButton").jqxDropDownButton("close");
	});
    var source = builddata();
    $("#jqxTree").jqxTree({source:source,width: 250 });
    $('#jqxTree').jqxTree('expandAll');
	$("input:radio[name=selLogo]").on("change",function(){
		if($('input:radio[name=selLogo]:checked').val() == 0)
		{
			$("#icon").removeAttr("disabled");
		} else {
			$("#icon").attr("disabled","disabled");
		}			
	});
	//$('#locationContainer').html($("#locationTemplate").html());
	$('#start_date_time').datetimepicker({ 
		showOn: "both",
		buttonImage: "<?php echo $this->baseUrl("images/calander.png");?>",
		buttonImageOnly: true,
		dateFormat: 'dd/mm/yy', 
		showSecond: false,
		timeFormat: 'hh:mm',
		firstDay:1
	});
	$('#end_date_time').datetimepicker({ 
		showOn: "both",
		buttonImage: "<?php echo $this->baseUrl("images/calander.png");?>",
		buttonImageOnly: true,
		dateFormat: 'dd/mm/yy', 
		showSecond: false,
		timeFormat: 'hh:mm',
		firstDay:1
	});
	// $('#stop_at_date').datetimepicker({ 
	// 	showOn: "both",
	// 	buttonImage: "<?php echo $this->baseUrl("images/calander.png");?>",
	// 	buttonImageOnly: true,
	// 	dateFormat: 'dd/mm/yy', 
	// 	showSecond: false,
	// 	timeFormat: 'hh:mm',
	// 	firstDay:1
	// });

	// $("#stop_by").on("change",function(){
	// 	if($(this).attr("value")==1) {
	// 		$( "#divDate" ).css("display","none");
	// 		$( "#divOcurrence" ).css("display","inline");
	// 		$( "#stop_at" ).attr("value",$("#stop_at_ocurrence").attr("value"));
	// 	} else {
	// 		$( "#divOcurrence" ).css("display","none");
	// 		$( "#divDate" ).css("display","inline");
	// 		$( "#stop_at" ).attr("value",$("#stop_at_date").attr("value"));
	// 	}
	// });
	// $( "#stop_at_date, #stop_at_ocurrence" ).on("change",function(){
	// 	$( "#stop_at" ).attr("value",$(this).attr("value"));
	// });
	// if($("#stop_by").val() == 1){
	// 	$("#stop_at_ocurrence").attr("value",$("#stop_at").val());
	// }else{
	// 	$("#stop_at_date").attr("value",$("#stop_at").val());
	// }

	$("#applyall").on("click",function(e){
		if(!e.isDefaultPrevented()){
	    	var promptus = new prompt({
	            	reference :"#frmAddEditEvent",
	                element : "#content",
	                message : "<?php echo $this->translate('Your changes will be saved and applied to all languages. Is it Ok?'); ?>",
	                buttons : {
	                    "Yes" : function(self){
		                    this.close();
		                    queryAppend = "&all=true";
	                        $("#submit").trigger("click");
	                    },
	                    "No"  : function(self){
	                    	this.close();
	                    },
	                }
	            });
	        e.preventDefault();
	    }
	});
	
	$("#frmAddEditEvent").validator().submit(function(e){
		if($('#module_events_category_id').val() == 0){
			promptus = new prompt({
	           	reference : form,
	            element : "#content",
	            beforeShow : function(){
	                this.alternateMessage = this.showErrorMessage("Please select some Category!");
                } 
			});
			setTimeout(function(){
				promptus.close();
			}, 2000);
			return false;
		}
		window.topush = false;
		if($("#sendpush").is(":checked")){
		    window.topush = true;	
		}
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Event...')?>");
	                }
	            });
	            next();
			}).queue(function(next){
				if($('input:radio[name=selLogo]:checked').val() == 0 && $('#icon').attr("value")!="") {
					$.ajaxFileUpload({
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:'icon',
						dataType: 'json',
						data:{iconupload:'true'},
						success: function (data, status)
						{
							if(data.success != undefined) {
								$("#icon_path").attr("value",data.success);
								next();
							}
						},
						error: function (data, status, e)
						{
							promptus.showErrorMessage("<?php echo $this->translate('Error uploading icon.')?>");
							setTimeout(function(){
								promptus.close();
							}, 2000);
							
						}
					});
				} else {
					next();
				}
			}).queue(function(next){
				if($('#image').attr("value")!="") {
					$.ajaxFileUpload({
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:'image',
						dataType: 'json',
						data:{upload:'true'},
						success: function (data, status)
						{
							if(data.success != undefined) {
								$("#image_path").attr("value",data.success);
								next();
							}
						},
						error: function (data, status, e)
						{
							promptus.showErrorMessage("<?php echo $this->translate('Error uploading image.')?>");
							setTimeout(function(){
								promptus.close();
							}, 2000);
							
						}
					});
				} else {
					next();
				}
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize() + queryAppend,
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
							next();
						} else if(json["success"] != undefined){
						    if(!window.topush){
						    	promptus.showSuccessMessage("<?php echo $this->translate('Event saved successfully.')?>");
								setTimeout(function(){
									location.href = "<?php echo $this->url(array("module"=>"events","controller"=>"index","action" => "index"),"default",true);?>";
								}, 2000);
						    }else{
						    	promptus.showSuccessMessage("<?php echo $this->translate('Event saved successfully and redirecting you to Push message.')?>");
								setTimeout(function(){
									location.href = "<?php echo $this->url(array("module"=>"push-message","controller"=>"index","action" => "add"),"default",true);?>/id/"+json["success"];
								}, 2000);
						    }
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
	$(".addEventLocation").on("click",function(){
		$("#hiddenPopup").dialog({
			modal:true,
			width:600,
			resizable:false,
			title:"Add Location"
		});
		if(!window.appended){
			var template = $('#locationTemplate').html();
			var data = {
				plzValue: null,
				cityValue: null,
				countryValue: null,
				addressValue: null,
				locationValue: null,
				latitudeValue: null,
				longitudeValue: null,
				id: window.rowNumber
			}
			var output = Mustache.render(template,data);
			$('#hiddenPopup').append(output);
			$('#hiddenPopup').find('.hrRepeat').remove();
			$('#hiddenPopup').find('.deleteLocation').remove();
			$('#hiddenPopup .locationInput').find("input[name='plz[]']").attr('id','map_plz');
			$('#hiddenPopup .locationInput').find("input[name='location[]']").attr('id','map_location');
			$('#hiddenPopup .locationInput').find("select[name='country[]']").attr('id','map_country');
			$('#hiddenPopup .locationInput').find("input[name='city[]']").attr('id','map_city');
			$('#hiddenPopup .locationInput').find("input[name='latitude[]']").attr('id','map_latitude');
			$('#hiddenPopup .locationInput').find("input[name='longitude[]']").attr('id','map_longitude');
			$('#hiddenPopup .locationBox').find("textarea[name='address[]']").attr('id','map_address');
			$('#hiddenPopup').append("<div class='singleEntry'>"+"<input type='button' value='submit' name='singleEntry' />"+"</div>");
			window.appended = true;
		$('#gMap').gmap3({
	    	action: 'init',
	        options:{
	        	center:[0, 0],
	        	mapTypeId: google.maps.MapTypeId.SATELLITE,
	        	zoom: 2,
	        	scrollwheel: false
	        },
	        callback: function(){
	            
	        }
	    });
	    // Set current geo-loaction on Map
	    if($("#map_latitude").attr("value")=="" && $("#map_longitude").attr("value")=="")
	    {
	    	var url = "http://www.geoplugin.net/json.gp?jsoncallback=?";

	    	$(document).queue(function(next){

	    		if(navigator.geolocation) {
	        		var locationMarker = null;
	        		navigator.geolocation.getCurrentPosition(function(position) {
	            		if(locationMarker) {
	    					return;
	            		}
	            		$('#gMap').gmap3('setDefault', {init:{center:[ position.coords.latitude,position.coords.longitude ]}});
	               		$("#map_latitude").attr("value",position.coords.latitude);
	           			$("#map_longitude").attr("value",position.coords.longitude);

	           			next();
	        		}, function() {
	        			
	        		});
	        	} 
	        	
	        	if($("#map_latitude").attr("value")=="" && $("#map_longitude").attr("value")=="") {

	        		$.getJSON(url, function(data){
	                	if(data['geoplugin_status'] == 200){
	            	        // Do something with the data
	            	    	$('#gMap').gmap3('setDefault', {init:{center:[ data["geoplugin_latitude"],data["geoplugin_longitude"] ]}});
	        				//$('#gMap').gmap3({action: 'setCenter', args:[ data["geoplugin_latitude"],data["geoplugin_longitude"] ]});
	                   		$("#map_latitude").attr("value",data["geoplugin_latitude"]);
	               			$("#map_longitude").attr("value",data["geoplugin_longitude"]);
	            	    }
	            	    else
	            	    {
	            	    	$('#gMap').gmap3('setDefault', {init:{center:[ 0,0 ]}});
	                   		$("#map_latitude").attr("value",0);
	               			$("#map_longitude").attr("value",0);
	            	    }
	            	}).complete(next);
	        	}
	    	}).queue(function(next){
	    

	    // Set Marker to the current geo-location
	   	$('#gMap').gmap3({ 
	        action: 'addMarker',
	        latLng:[$("#map_latitude").attr("value"),$("#map_longitude").attr("value")],
			options:{
	        	draggable: true,
	            animation: google.maps.Animation.DROP
	        },
	        events:{
	        	drag: function(marker, event, data) {
	        		var pos = marker.getPosition();
	            	$("#map_latitude").attr("value",pos.lat());
	            	$("#map_longitude").attr("value",pos.lng());
	        	}
	        }
	    });
		next();
	    });    	
	    } else {
	    	// Set Marker to the current geo-location
	    	$("#mark-fixed").removeAttr("checked");
	       	$('#gMap').gmap3({ 
	            action: 'addMarker',
	            latLng:[$("#map_latitude").attr("value"),$("#map_longitude").attr("value")],
				options:{
	            	draggable: true,
	                animation: google.maps.Animation.DROP
	            },
	            events:{
	            	drag: function(marker, event, data) {
	            		var pos = marker.getPosition();
	                	$("#map_latitude").attr("value",pos.lat());
	                	$("#map_longitude").attr("value",pos.lng());
	            	}
	            }
	        });
	       	$('#gMap').gmap3({
			    action:"panTo",
			    args: [new google.maps.LatLng($("#map_latitude").attr("value"),$("#map_longitude").attr("value"))]
	        });
			var map = $('#gMap').gmap3("get");
			map.setZoom(10);
	    }
	    // Callback to auto set marker based on address
	    $("#map_address, #map_city, #map_plz, #map_country").on("blur",function(){
	    	if($("#mark-fixed").attr("checked")!="checked") return;
	    	$('#gMap').gmap3({
	    		action:'getAddress',
	    		address:($("#map_address").attr("value")+ " " + $("#map_plz").attr("value")+ " " + $("#map_city").attr("value")+ " " + $("#map_country").attr("value")),
	    		callback:function(results){
	    			if (!results) return;
	    			var item = results[0];
	    			$("#gMap").gmap3(
	    	    		{action:'clear', name:'marker'},
	    				{
	        				action:'addMarker',
	    					latLng:item.geometry.location,
	    					options:{
	  				        	draggable: true,
	  				        	animation: google.maps.Animation.DROP
	  				        },
	  				        events:{
	  				        	drag: function(marker, event, data) {
	  				        		var pos = marker.getPosition();
	  				            	$("#map_latitude").attr("value",pos.lat());
	  				            	$("#map_longitude").attr("value",pos.lng());
	  				        	}
	  				        }
	    				}
	        		);
	    			var pos = item.geometry.location;
	            	$("#map_latitude").attr("value",pos.lat());
	            	$("#map_longitude").attr("value",pos.lng());
	                	
	       			$('#gMap').gmap3({
	       			    action:"panTo",
	       			    args: [new google.maps.LatLng($("#map_latitude").attr("value"),$("#map_longitude").attr("value"))]
	        		});
	       			var map = $('#gMap').gmap3("get");
	       			map.setZoom(10);
	    		}
	    	});
		});
		
	    // Callback to auto set marker based on latitude and longitude
	    $("#map_latitude,#map_longitude").on("blur",function(){
	    	if($("#mark-fixed").attr("checked")!="checked") return;
	        $("#gMap").gmap3(
				{action:'clear', name:'marker'},
				{
	    			action:'addMarker',
					latLng:[$("#map_latitude").attr("value"),$("#map_longitude").attr("value")],
					options:{
						draggable: true,
						animation: google.maps.Animation.DROP
					},
					events:{
						drag: function(marker, event, data) {
					    	var pos = marker.getPosition();
					        $("#map_latitude").attr("value",pos.lat());
					        $("#map_longitude").attr("value",pos.lng());
						}
					}
				}
			);
	        $('#gMap').gmap3({
			    action:"panTo",
			    args: [new google.maps.LatLng($("#latitude").attr("value"),$("#longitude").attr("value"))]
	        });
			var map = $('#gMap').gmap3("get");
			map.setZoom(10);
		});
		}
		$("#hiddenPopup input,#hiddenPopup select,#hiddenPopup textarea").not($("#hiddenPopup input[name='singleEntry'],#hiddenPopup input[type='checkbox']")).each(function(){
			$(this).val("");
		});
	});
	$(".singleEntry").live("click",function(){
		window.rowNumber =  window.rowNumber ? window.rowNumber :  $('#locationContainer .locationBox').length;
		var data = {
			locationValue: $("#map_location").attr("value"),
			latitudeValue: $("#map_latitude").attr("value"),
			longitudeValue: $("#map_longitude").attr("value"),
			plzValue: $("#map_plz").attr("value"),
			cityValue: $("#map_city").attr("value"),
			addressValue: $("#map_address").attr("value"),
			id: window.rowNumber
		}
		var template = $('#locationTemplate').html();
		var output = Mustache.render(template,data);	

		$('#locationContainer').append(output);
		$("#locationContainer").find('*[id="country"]:last option[value="'+$('#map_country').val()+'"]').attr("selected","selected");
		window.rowNumber++;
		$("#hiddenPopup").dialog("close");
	});

	$(".loadEventLocation").on("click",function(){
		var promptus = false;
    	var self = this;
		$(document).queue(function(next){
			promptus = new prompt({
            	reference : self,
                element : "#mainContainer",
                beforeShow : function(){
	                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Fetching Your Office Locations...'); ?>");
                }            
            });
            next();            
		}).queue(function(next){
	    	$.ajax({
	            url: "<?php echo $this->url(array("module"=>"events","controller"=>"index","action"=>"load-contacts")); ?>",
	            cache: false,
	            type: "POST",
	            success:function(data){
	            	$("#gridDialog").html(data).dialog({
						modal:true,
						width:700,
						resizable:false,
						title:"Add Locations"
					});
	            	next();
	            }
	        });
	         
		}).queue(function(next){
			$(".importLoadedContacts").on("click",function(){
				var selectedElement = $("#dataGridReorder input[name='contact[]']:checked");
				if(selectedElement.length != ""){
					selectedElement.each(function(){
					    window.rowNumber =  window.rowNumber ? window.rowNumber :  $('#locationContainer .locationBox').length;
					    var tr = $(this).parents("tr");
					    var data = {
					    	locationValue: tr.find("td:nth-child(3)").html(),
					    	addressValue: tr.find("td:nth-child(4)").html(),
							cityValue: tr.find("td:nth-child(5)").html(),
							countryValue: tr.find("td:nth-child(6)").html(),
							plzValue: tr.find("td:nth-child(7)").html(),
							latitudeValue: tr.find("td:nth-child(8)").html(),
							longitudeValue: tr.find("td:nth-child(9)").html(),
							id: window.rowNumber
						}
						var template = $('#locationTemplate').html();
					    var output = Mustache.render(template,data);
					    $('#locationContainer').append(output);
					    $("#locationContainer").find('*[id="country"]:last option[value="'+tr.find("td:nth-child(6)").html()+'"]').attr("selected","selected");
						window.rowNumber++;
						$("#gridDialog").dialog("close");
					});
				}else{
					promptus = new prompt({
		           	reference : self,
		            element : "#gridDialog",
		            beforeShow : function(){
		                this.alternateMessage = this.showErrorMessage("You have not selected any Location!");
                } 
			});
			setTimeout(function(){
	  	        promptus.close();
	  		}, 1000);
		}
			});
			promptus.close();
			next();
  		});
	});
	
	$('.deleteLocation').live("click",function(){
		$(this).removeClass("deleteLocation");
		var deletedRow = $(this).attr("class").replace("delete-",'');
		$("#record-"+deletedRow).remove();
	});
	
	var data = <?php echo ($this->location=="")? "[]": $this->location; ?>;
	window.rowNumber =  window.rowNumber ? window.rowNumber :  $('#locationContainer .locationBox').length;
	for(x in data){
		obj = data[x];
		if(typeof(obj) == "object"){				
			tmpTemplate = $("#locationTemplate").html();
			 var dbData = {
			plzValue: obj.plz,
			cityValue: obj.city,
			addressValue: obj.address,
			locationValue: obj.location,
			countryValue: obj.country,
			latitudeValue: obj.latitude,
			longitudeValue: obj.longitude,
			id: window.rowNumber
			}
		    var output = Mustache.render(tmpTemplate,dbData);
			$('#locationContainer').append(output);
			$("#locationContainer").find('*[id="country"]:last option[value="'+obj.country+'"]').attr("selected","selected");
			window.rowNumber++;
		}	
	}
	$("#stop_by").trigger("change");
});

// -->
function selectAll() {
	if($("#chkSelectAll").attr("checked") == "checked") {
		$(".contact").attr("checked","checked");
    } else {
    	$(".contact").removeAttr("checked");
    }
}
</script>
<div id="gridDialog">
</div>