<?php $form = $this->form; ?>
<script>
window.totalcategories = <?php echo $this->totalcategories?$this->totalcategories:0;?>;
</script>
<style type="text/css">
<!--
#language_id {
	min-width:172px !important;
	height: 130px;
}
-->
</style>
<form id="frmFilter">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Filter'); ?></h2></td>
          <td>
            <table>
              <tr>
                <td><?php echo $this->translate('Title'); ?></td>
                <td><input type="text" class="input" id="txtTemplate" name="ed[title]"></td>
                <td><?php echo $this->translate('Time'); ?></td>
                <td>
                	<select name="time">
                		<option value="">Select Events Time</option>
                		<option value="1">Past Events</option>
                		<option value="2" selected="selected">Current Events</option>
                	</select>
                </td>
                <td><?php echo $this->translate('Status'); ?></td>
                <td>
                    <select name="status">
                        <option value="1"><?php echo $this->translate('Active'); ?></option>
                        <option value="0"><?php echo $this->translate('InActive'); ?></option>
                    </select>
                </td>
              </tr>
            </table>
          </td>
          <td>&nbsp;</td>
          <td align="right">
            <input type="submit" name="button" id="button" class="button" value="<?php echo $this->translate('Submit')?>" /> &nbsp;
            <input type="button" name="bulkEdit" id="bulkEdit" class="button" value="<?php echo $this->translate('Bulk Edit')?>" />
          </td>
        </tr>
      </table>
</div>
</form>
<a class="togglefilter"></a>
<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGrid">
    <thead>
        <tr>
            <th scope="col"><input type="checkbox" name="check_all" id="check_all" value="select all" /></th>
            <th scope="col"><?php echo $this->translate('Title'); ?></th>
            <th scope="col"><?php echo $this->translate('Type'); ?></th>
            <th scope="col"><?php echo $this->translate('Category'); ?></th>
            <th scope="col"><?php echo $this->translate('Start Date/Time'); ?></th>
            <th scope="col"><?php echo $this->translate('End Date/Time'); ?></th>
            <th scope="col"><?php echo $this->translate('Status'); ?></th>
            <th scope="col"><?php echo $this->translate('Order'); ?></th>
            <th scope="col" class="action"><?php echo $this->translate('Action'); ?></th>
        </tr>
    </thead> 
    <tbody>
        <tr>
            <td colspan="3" class="dataTables_empty"><?php echo $this->translate('Loading data from server'); ?></td>
        </tr>
    </tbody>      
</table>
<div id="divBulkEdit" style="display: none;">
<form id="frmBulkEdit" name="frmBulkEdit" method="post">
	<table>
		<tr>
			<td><?php echo $form->language_id->renderLabel() ?></td>
			<td><?php echo $form->language_id->renderViewHelper()?></td>
		</tr>
		<tr>
			<td><?php echo $form->start_date_time->renderLabel() ?></td>
			<td><?php echo $form->start_date_time->renderViewHelper()?></td>
		</tr>
		<tr>
			<td><?php echo $form->end_date_time->renderLabel() ?></td>
			<td><?php echo $form->end_date_time->renderViewHelper()?></td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
		<tr>
			<td colspan="2" align="center">
				<?php echo html_entity_decode($form->submit->renderViewHelper())?>&nbsp;
				<?php echo html_entity_decode($form->reset->renderViewHelper())?>
			</td>
		</tr>
	</table>
</form>
</div>
<script type="text/javascript">
var grid ="";
$(document).ready(function() {
	$('a[href="<?php echo $this->addlink;?>"]').on('click',function(e){
		if(!e.isDefaultPrevented()){
			if(window.totalcategories == 0){
				 promptus = new prompt({
	                reference : self,
	                element : ".dataTables_wrapper"
	            });
	            promptus.showErrorMessage("You can not add an event without category.Please add atleast one category.");
	            setTimeout(function(){
            		promptus.close();
                }, 3000);
				e.preventDefault();
			}
		}
	});
    grid = dataTable({
        aaSorting: [[ 3, "asc" ]],
        "aoColumns": [
						{ "sName": "checkbox", "bSortable": false},
                        { "sName": "ed.title" },
                        { "sName": "et.title" },
                        { "sName": "ecd.title" },
                        { "sName": "ed.start_date_time" },
                        { "sName": "ed.end_date_time" },
                        { "sName": "e.status" },
                        { "sName": "e.order" },
                        { "sName": "actions","bSortable": false}
                     ],
        id : $('#dataGrid'),
        filterForm : $('#frmFilter'),
        sAjaxSource: "<?php echo $this->url(array("module"=>"events","controller"=>"index","action"=>"grid"));?>"
    });
    $('#start_date_time').datetimepicker({ 
		showOn: "both",
		buttonImage: "<?php echo $this->baseUrl("images/calander.png");?>",
		buttonImageOnly: true,
		dateFormat: 'dd/mm/yy', 
		showSecond: false,
		timeFormat: 'hh:mm',
		firstDay:1
	});
	$('#end_date_time').datetimepicker({ 
		showOn: "both",
		buttonImage: "<?php echo $this->baseUrl("images/calander.png");?>",
		buttonImageOnly: true,
		dateFormat: 'dd/mm/yy', 
		showSecond: false,
		timeFormat: 'hh:mm',
		firstDay:1
	});
    $(document).on("submit","#frmFilter",function(){
        grid.fnDraw();
        return false;
    });
    $(document).on("click","#check_all",function(e){
        if(typeof $(this).attr("checked") !== 'undefined') {
			$(".check-box").attr("checked","checked");
		} else {
			$(".check-box").removeAttr("checked");
		}
    });
    $(".check-box").live("click",function(e){
		if(typeof $(this).attr("checked") !== 'undefined') {
			if($(".check-box:checked").length==$(".check-box").length) {
				$("#check_all").attr("checked","checked");
			}
		} else {
			$("#check_all").removeAttr("checked");
		}
	});
    $(document).on("click","#bulkEdit",function(e){
    	if($(".check-box:checked").length==0) {
			alert("Please Select Records To Perform Bulk Edit.");
			return;
    	}
    	$("#frmBulkEdit #reset").click();
    	$("#divBulkEdit").dialog({
    		modal: true,
    		width: 450,
    		resizable: false,
    		title: "<?php echo $this->translate("Bulk Edit")?>",
    		dialogClass: "Add"
    	});
    });
    $("#frmBulkEdit").validator().submit(function(e){
    	var self = this;
    	var form = $(this);
    	var queryAppend = "";
    	$(".check-box:checked").each(function(){
    		queryAppend += "&module_events_id[]=" + $(this).val();
        });
        if(!e.isDefaultPrevented()){
            var promptus=false;
        	$(document).queue(function(next){
        		promptus = new prompt({
	            	reference : form,
	                element : "#divBulkEdit",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Event...'); ?>");
	                }
	            });
                next();
            }).queue(function(next){
                $.ajax({
                    url: '<?php  echo $this->url(array("module"=>"events","controller"=>"index","action"=>"bulk-edit")); ?>',
                    cache: false,
                    data : form.serialize() + queryAppend,
                    type: "POST",
                    dataType: "json",
                    success: function(json){
                        if(json.success != undefined){ 
                        	promptus.showSuccessMessage("<?php echo $this->translate('Event saved successfully.'); ?>");
                        	setTimeout(function(){
                        		promptus.close();
                        		$('#divBulkEdit').dialog("close");
                        		$("#frmBulkEdit #reset").click();
                        		grid.fnDraw();
                            }, 1000);
                        } else if(json.errors != undefined){
                            var errorMessage = "<?php echo $this->translate('Unable to save event:'); ?><br />";
                            errorMessage += json.errors.message;
                            promptus.showErrorMessage(errorMessage);
                        	setTimeout(function(){
                        		promptus.close();
                            }, 2000);
                        }
                    },
                    error: function(){
                    }
                }).complete(next); 
            });
            e.preventDefault();
        }
    });
    $(document).on("click",".grid_delete",function(e){
        var self = this;
        window.currentDeleteUrl = $(this).attr("href"); 
        if(!e.isDefaultPrevented()){
            var promptus = new prompt({
                        reference : self,
                        element : ".dataTables_wrapper",
                        message : "<?php echo $this->translate('Are you sure you want to delete this Event?'); ?>",
                        buttons : {
                            "Yes" : function(self){
                                var prompt = this;
                                $(document).queue(function(next){
                                    prompt.showLoadingMessage("<?php echo $this->translate('Please wait while deleting event..'); ?>");
                                    next();
                                }).queue(function(next){
                                    $.ajax({
                                        url: window.currentDeleteUrl,
                                        cache: false,
                                        type: "GET",
                                        dataType: "json",
                                        success: function(json){
                                            if(json.success != undefined){ 
                                                prompt.showSuccessMessage("<?php echo $this->translate('Event deleted successfully.'); ?>");
                                                setTimeout(function(){
                                                    prompt.close();
                                                    grid.fnDraw();
                                                }, 1000);
                                            } else if(json.errors != undefined){
                                                var errorMessage = "<?php echo $this->translate('Unable to delete event:'); ?><br />";
                                                errorMessage += json.errors.message;
                                                prompt.showErrorMessage(errorMessage);
                                                setTimeout(function(){
                                                    prompt.close();
                                                }, 2000);
                                            }
                                        },
                                        error: function(){
                                        }
                                    }).complete(next); 
                                });
                            },
                            "No"  : function(self){
                                this.close();
                            },
                        }
                    });
            e.preventDefault();
        }
    });

    $(document).on("click",".module_publish",function(e){
        var self = this;
        window.currentPublishUrl = $(this).attr("href"); 
        if(!e.isDefaultPrevented()){
        	var promptus = new prompt({
                    	reference : self,
                        element : ".dataTables_wrapper",
                        message : "<?php echo $this->translate('Are you sure you want to publish this Module?'); ?>",
                        buttons : {
                            "Yes" : function(self){
                                var prompt = this;
                                $(document).queue(function(next){
                                    prompt.showLoadingMessage("<?php echo $this->translate('Publishing Module..'); ?>");
                                    next();
                                }).queue(function(next){
                                    $.ajax({
                                        url: window.currentPublishUrl,
                                        cache: false,
                                        type: "GET",
                                        dataType: "json",
                                        success: function(json){
                                            if(json.success != undefined){ 
                                            	prompt.showSuccessMessage("<?php echo $this->translate('Module Published successfully.'); ?>");
                                            	setTimeout(function(){
                                            		prompt.close();
                                                	grid.fnDraw();
                                                }, 1000);
                                            } else if(json.errors != undefined){
                                                var errorMessage = "<?php echo $this->translate('Unable to publish Module:'); ?><br />";
                                                errorMessage += json.errors.message;
                                            	prompt.showErrorMessage(errorMessage);
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 2000);
                                            }
                                        },
                                        error: function(){
                                        }
                                    }).complete(next); 
                                });
                            },
                            "No"  : function(self){
                            	this.close();
                            },
                        }
                    });
            e.preventDefault();
        }
    });
    
    $('.togglefilter').on("click",function(){
		$('#filterBox').toggle();
		$('#content > a').toggleClass('flip-vertical');
	});
	$('#filterBox').hide();
});
</script>