<?php
class ModuleImageGallery1_Model_Mapper_ModuleImageGalleryCategoryDetail1 extends Standard_ModelMapper{
	protected $_dbTableClass = "ModuleImageGallery1_Model_DbTable_ModuleImageGalleryCategoryDetail1";
}