<?php $form = $this->form; ?>
<style type="text/css">
<!--

-->
</style>
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
          <td align="right"><h2><?php echo $this->language; ?></h2></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditSocialMedia" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php echo $form->module_social_media_id->renderViewHelper(); ?>
	<?php echo $form->module_social_media_detail_id->renderViewHelper(); ?>
	<?php echo $form->language_id->renderViewHelper(); ?>
	<table style="margin:10px 0;">
		<tbody>
			<tr>
		    	<td><?php echo $form->social_media_type_id->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->social_media_type_id->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->title->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->title->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->url->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->url->renderViewHelper()?>
				</td>
			</tr>
			<tr>
				<td valign="top">
					<label><?php echo $this->translate('Icon:')?></label>
				</td>
				<td valign="top">
					<div id="lstLogo" class="logo-box">
						<?php
							$resource_path = $this->baseUrl("resource/social-media/icons");
							$types = $this->types;
							foreach($types as $t) {
								$icons = $this->icons;
								foreach($icons as $i) {
									if($i->getSocialMediaTypeId() == $t->getSocialMediaTypeId()) {
						?>
										<div class="icons icon-group-<?php echo $t->getSocialMediaTypeId(); ?>">
											<label for="selLogo_<?php echo $i->getSocialMediaIconId(); ?>">
												<img src="<?php echo $resource_path . "/" . $i->getIconPath(); ?>" width="64" />
											</label>
											<input type="radio" id="selLogo_<?php echo $i->getSocialMediaIconId(); ?>" name="selLogo" value="<?php echo $i->getSocialMediaIconId(); ?>" />
										</div>
						<?php 
									}
								}
							}
						?>
					</div>
				</td>
			</tr>
			<tr>
				<td style="padding-left: 20px;">
				</td>
				<td>
					<div class="logo-box">
						<table>
						<tr>
							<td>
								<?php 
					        	if($this->icon_src!="") {
					        	?>
					        	<img alt="" src="<?php echo $this->icon_src;?>" style="width: 64px;" />
					        	<?php 
					        	}
					        	?>
				        	</td>
				        	<td>
				        		<?php
				        		$checked = "";
					        	if($this->icon_src!="") {
					        		$checked = "checked='checked'";
								}
								?>
					        	
								<input type="radio" id="selLogo_0" <?php echo $checked; ?> name="selLogo" value="0" style="margin-left: 10px;" />
								<label for="selLogo_0"><?php echo $this->translate('Upload:')?></label>
								<input id="icon" type="file" name="icon" /> (Size: 120px &#215; 120px )
					        	<input id="icon_path" type="hidden" name="icon_path" value="" />
				        	</td>
			        	</tr>
			        	</table>
		        	</div>
				</td>
			</tr>
			<tr>
			    	<td><?php echo $form->status->renderLabel() ?></td>
			        <td>
			        	<?php echo $form->status->renderViewHelper()?>
					</td>
			</tr>
			<tr>
		        <td colspan="3" align="center">
		        	<?php echo $form->submit->renderViewHelper() ?>&nbsp;
					<?php echo $form->reset->renderViewHelper() ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$("#social_media_type_id").on("change",function(){
		$(".icons").hide();
		if($('input:radio[name=selLogo]:checked').val() != 0) {
			$("input:radio").removeAttr("checked");
		}
		$(".icon-group-"+$("#social_media_type_id").val()).css("display","inline-block");
	});
	$(".icon-group-"+$("#social_media_type_id").val()).css("display","inline-block");
	
	$("input:radio[name=selLogo]").on("change",function(){
		if($('input:radio[name=selLogo]:checked').val() == 0)
		{
			$("#icon").removeAttr("disabled");
		} else {
			$("#icon").attr("disabled","disabled");
		}			
	});
	
	if($('input:radio[name=selLogo]:checked').val() != 0)
	{
		$("#icon").attr("disabled","disabled");
	}
	
	$("#frmAddEditSocialMedia").validator().submit(function(e){
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Social Media...')?>");
	                }
	            });
	            next();
			}).queue(function(next){
				if($('input:radio[name=selLogo]:checked').val() == 0 && $('#icon').attr("value")!="") {
					$.ajaxFileUpload({
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:'icon',
						dataType: 'json',
						data:{upload:'true'},
						success: function (data, status)
						{
							if(data.success != undefined) {
								$("#icon_path").attr("value",data.success);
								next();
							}
						},
						error: function (data, status, e)
						{
							promptus.showErrorMessage("<?php echo $this->translate('Error uploading icon.')?>");
							setTimeout(function(){
								promptus.close();
							}, 2000);
							
						}
					});
				} else {
					next();
				}
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize(),
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
							next();
						} else if(json["success"] != undefined){
							promptus.showSuccessMessage("<?php echo $this->translate('Social Media saved successfully.')?>");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"social-media","controller"=>"index","action" => "index"),"default",true);?>";
							}, 2000);
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
});
// -->
</script>