<?php
	$form = $this->form;
?>
<form id="defaultlogin" class="box login" method="<?php echo $form->getMethod() ?>" 
		action="<?php echo $this->url(array("module"=>"default","controller"=>"login","action"=>"index"))?>">
    <fieldset class="boxBody">
	<?php
		if(isset($this->loginMessage))
		{
		?>
		<label class="errors"><?php echo $this->loginMessage; ?></label>
		<?php 
		}
	?>
	<?php echo $form->username->renderLabel() ?>
	  <?php echo $form->username->renderViewHelper(); ?>
	  <?php echo $form->password->renderLabel() ?>
	  <?php echo $form->password->renderViewHelper() ?><label class="forgot"><a href="<?php echo $this->url(array("module"=>"default","controller"=>"forgot","action"=>"index"))?>" class="rLink" tabindex="5"><?php echo $this->translate("Forget your password?") ?></a></label>
	</fieldset>
	<footer>
	  <?php echo $form->remember->renderViewHelper()." ";?><?php echo $form->remember->renderLabel(); ?>
	  <?php echo $form->offset->renderViewHelper(); ?>
	  <?php echo $form->submit->renderViewHelper() ?>
	</footer>
</form>

<script type="text/javascript">
$(document).ready(function() {
	$("#password").attr("value","<?php echo $this->password; ?>");
	var offset = new Date().getTimezoneOffset();
	$("form").validator().submit(function(){
		$("#offset").attr("value",offset);
	});
});
</script>