<?php header('Content-type: text/html; charset=utf-8'); ?>
<?php echo $this->doctype('HTML5');?>
<html>
<head>
<?php echo $this->headTitle("AppStart");?>
<?php 
	echo $this->headLink()
			->appendStylesheet($this->baseUrl('css/style.css'))
			->appendStylesheet($this->baseUrl('css/structure.css'))
			->appendStylesheet($this->baseUrl("libs/DataTables/css/data_table.css"))
			->appendStylesheet($this->baseUrl('css/jquery.tools.css'))
			->appendStylesheet($this->baseUrl('libs/Prompt/css/prompt.css'))
			->appendStylesheet($this->baseUrl('libs/jqueryui/css/ui.multiselect.css'))
			->appendStylesheet($this->baseUrl('libs/jqueryui/css/jqueryui.smoothness.custom.css'))
			->appendStylesheet($this->baseUrl('libs/timepicker/jquery-ui-timepicker-addon.css'));
	 echo $this->headScript()
			->appendFile($this->baseUrl('libs/html5/html5.js'),'text/javascript', array('conditional' => 'lt IE 9'))
			->appendFile($this->baseUrl("js/jquery-1.8.0.min.js"))
			->appendFile($this->baseUrl("libs/blockUI/jquery.blockUI.js"))
			->appendFile($this->baseUrl("js/jquery.tools.min.js"))
			->appendFile($this->baseUrl("libs/jqueryui/js/jqueryui.smoothness.min.js"))
			->appendFile($this->baseUrl("libs/DataTables/js/jquery.dataTables.min.js"))
			->appendFile($this->baseUrl("libs/DataTables/js/dataTables.aksPlugin.js"))
			->appendFile($this->baseUrl("libs/Prompt/js/prompt.js"))
	 		->appendFile($this->baseUrl("libs/jqueryui/js/ui.multiselect.js"))
	 		->appendFile($this->baseUrl("libs/timepicker/jquery-ui-timepicker-addon.js"));
	 
	 $activeLang = Standard_Functions::getAdminActiveLanguage();
?>
<script type="text/javascript">
window.dataTableLangUrl = "<?php echo $this->baseUrl("libs/DataTables/lang/".$activeLang->getLang().".txt"); ?>";
</script>
</head>
<body>
<div id="wrapper">
  <header id="header">
    <h1></h1>
    <nav id="top-nav" >
      <ul>
      	<li>
      		<div id="language">
      			<?php 
      			$languages = Standard_Functions::getAllLanguages();
      			
      			if(is_array($languages) && $activeLang) {
				?>
						<div class="language-item active">
						<img alt="<?php echo $activeLang->get("title"); ?>" src="<?php echo $this->baseUrl("images/lang/".$activeLang->get("logo")); ?>" />
						<?php echo $activeLang->get("title"); ?>
	      				</div>
				<?php 
					foreach($languages as $lang) {
						if($lang["language_id"] != $activeLang->getLanguageId()) {
				?>
						<div class="language-item">
						<a href="javascript:void(0);" onclick="changeLocale('<?php echo $lang["language_id"]; ?>');"><img alt="<?php echo $lang["title"]; ?>" src="<?php echo $this->baseUrl("images/lang/".$lang["logo"]); ?>" /><?php echo $lang["title"]; ?></a>
	      				</div>
				<?php 
						}
      				} 
				} ?>
      		</div>
      	</li>
        <li class="current"><a href="#"><?php echo $this->translate('Welcome');?> <span><?php echo (Standard_Functions::getCurrentUser()->role_id == 1) ? $this->translate('Admin') : $this->translate('System User'); ?></span> </a></li>
        <li class="logout"><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'login','action'=>'logout'),null,true);?>"  > <?php echo $this->translate('Logout');?></a></li>
      </ul>
    </nav>
    <div style="clear:both;"></div>
    <nav id="main-nav">
      <?php echo $this->navigation()->menu()->setPartial(array("navigation.phtml","admin")) ?> 
    </nav>
    
    <!-- with images -->
    <div id="breadcrumb">
      <?php echo $this->navigation()
  				  ->breadcrumbs()
  				  ->setMinDepth(0)
  				  ->setLinkLast(false)
  				  ->setRenderInvisible(true)
  				  ->setSeparator("")
      			  ->setPartial(array("breadcrumb.phtml","admin")); ?>
    </div>
    <?php 
    	if($this->addlink) {
    ?>
    	<div id="addlink">
    		<a href="<?php echo $this->addlink; ?>"><?php echo $this->translate("Add New") ?></a><span></span>
    	</div>
    <?php 
	} ?>
  </header>
  <!-- #header-->
  <div style="clear:both;"></div>
  <div id="content">
    <?php echo $this->layout ()->content; ?>
    <br style="clear:both" />
  </div>
  <!-- #content-->
  
<footer id="footer"> <?php echo $this->translate('Powered by:')?> <a href = "http://prostart.ch">prostart consulting gmbh</a></footer>
    <!-- #footer --> 
  
</div>
<!-- #wrapper -->
<script type="text/javascript">
// <!--
	function changeLocale(language_id) {
		var promptus = false;
		$(document).queue(function(next){
			promptus = new prompt({
            	reference : $("body"),
                element : "#content",
                beforeShow : function(){
	                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Changing language, please wait')?>");
                }
            });
            next();
		}).queue(function(next){
			$.ajax({
				type : "POST",
				cache : false,
				data : {'language_id':language_id},
				url : "<?php echo $this->url(array('module'=>'admin','controller'=>'index','action'=>'change-locale'),"default",true);?>",
				success : function(json){
					if(json["errors"] != undefined){
						promptus.showErrorMessage("<?php echo $this->translate('Error while changing language.')?>");
						next();
					} else {
						location.href = location.href;
					}
				},
				error : next
  			});
		}).queue(function(next){
			promptus.close();
			next();
  		});
	}
// -->
</script>
</body>
</html>