<?php header('Content-type: text/html; charset=utf-8'); ?>
<?php echo $this->doctype('HTML5');?>
<script>
window.publicUrl = '<?php echo $this->publicUrl; ?>';
</script>
<style>
.versionTitle{
  display:inline;
  display:inline-block;
  width: 86px;
  padding: 5px;
  vertical-align: top; 
}

.versionDescription{
  display:inline;
  display:inline-block;
  width: 300px;
  padding: 5px; 
}
#footer-version a:hover{
  cursor: pointer;
}
.loadMoreVersion{
  font-size: 11px;
  float: right;
}
.loadMoreVersion:hover{
  cursor: pointer;
}
</style>
<html>
<head>
<?php echo $this->headTitle("AppStart");?>
<?php 
	echo $this->headLink()
			->appendStylesheet($this->baseUrl('css/style.css'))
			->appendStylesheet($this->baseUrl('css/structure.css'))
			->appendStylesheet($this->baseUrl("libs/DataTables/css/data_table.css"))
			->appendStylesheet($this->baseUrl('css/jquery.tools.css'))
			->appendStylesheet($this->baseUrl('libs/Prompt/css/prompt.css'))
			->appendStylesheet($this->baseUrl('libs/jqueryui/css/ui.multiselect.css'))
			->appendStylesheet($this->baseUrl('libs/jqueryui/css/jqueryui.smoothness.custom.css'))
			->appendStylesheet($this->baseUrl('libs/jqwidget/css/jqx.base.css'))
			->appendStylesheet($this->baseUrl('libs/timepicker/jquery-ui-timepicker-addon.css'))
			->appendStylesheet($this->baseUrl('css/menu.css'));
	
	echo $this->headScript()
				//->appendFile("http://maps.google.com/maps/api/js?sensor=false")
				->appendFile($this->baseUrl('libs/html5/html5.js'),'text/javascript', array('conditional' => 'lt IE 9'))
				->appendFile($this->baseUrl("js/jquery-1.8.0.min.js"))
				->appendFile($this->baseUrl("js/ajaxfileupload.js"))
				->appendFile($this->baseUrl("js/gmap3.min.js"))
				->appendFile($this->baseUrl("libs/blockUI/jquery.blockUI.js"))
				->appendFile($this->baseUrl("js/jquery.tools.min.js"))
				->appendFile($this->baseUrl("libs/jqueryui/js/jqueryui.smoothness.min.js"))
				->appendFile($this->baseUrl("libs/DataTables/js/jquery.dataTables.min.js"))
				->appendFile($this->baseUrl("libs/DataTables/js/dataTables.aksPlugin.js"))
				->appendFile($this->baseUrl("libs/Prompt/js/prompt.js"))
				->appendFile($this->baseUrl("libs/jqueryui/js/ui.multiselect.js"))
				->appendFile($this->baseUrl("libs/timepicker/jquery-ui-timepicker-addon.js"))
                ->appendFile($this->baseUrl("libs/mustache/mustache.js"));

$activeLang = Standard_Functions::getActiveLanguage();
?>
<script type="text/javascript">
window.dataTableLangUrl = "<?php echo $this->baseUrl("libs/DataTables/lang/".$activeLang->getLang().".txt"); ?>";
</script>			
</head>
<body>
<div id="wrapper">
  <header id="header">
    <h1></h1>
    <nav id="top-nav" >
      <ul>
      	<li>
      		<div id="language">
      			<?php 
      			$languages = Standard_Functions::getCustomerLanguages();
      			
      			if(is_array($languages) && $activeLang) {
				?>
						<div class="language-item active">
						<img alt="<?php echo $activeLang->get("title"); ?>" src="<?php echo $this->baseUrl("images/lang/".$activeLang->get("logo")); ?>" />
						<?php echo $activeLang->get("title"); ?>
	      				</div>
				<?php 
					foreach($languages as $lang) {
						if($lang["language_id"] != $activeLang->getLanguageId()) {
				?>
						<div class="language-item">
						<a href="javascript:void(0);" onclick="changeLocale('<?php echo $lang["language_id"]; ?>');"><img alt="<?php echo $lang["title"]; ?>" src="<?php echo $this->baseUrl("images/lang/".$lang["logo"]); ?>" /><?php echo $lang["title"]; ?></a>
	      				</div>
				<?php 
						}
      				} 
				} ?>
      		</div>
      	</li>
        <li class="current"><a href="#"><?php echo $this->translate('Welcome')?> <span><?php echo isset(Standard_Functions::getCurrentUser()->name) ? Standard_Functions::getCurrentUser()->name : "User"; ?></span> </a></li>
        <li class="logout"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'login','action'=>'logout'),null,true);?>"  ><?php echo $this->translate('Logout')?></a></li>
      </ul>
    </nav>
    <div style="clear:both;"></div>
    <nav id="main-nav">
      <?php echo $this->navigation()->menu()->setPartial(array("navigation.phtml","default")) ?> 
    </nav>
    
    <!-- with images -->
    <div id="breadcrumb">
      <?php echo $this->navigation()
  				  ->breadcrumbs()
  				  ->setMinDepth(0)
  				  ->setLinkLast(false)
  				  ->setRenderInvisible(true)
  				  ->setSeparator("")
      			  ->setPartial(array("breadcrumb.phtml","default")); ?>
    </div>
    <?php 
    	if($this->addlink) {
    ?>
    	<div id="addlink">
    		<?php if($this->bulkupload) { ?>
    			<a id="hrefBlukUpload" href="<?php echo $this->bulkupload; ?>"><?php echo $this->translate('Bulk Upload');?></a><span></span>
    		<?php }?>
    		<?php if($this->explorer) { ?>
    			<a id="hrefExplorer" href="<?php echo $this->explorer; ?>"><?php echo $this->translate('Explorer View');?></a><span></span>
    		<?php }?>
			<?php if($this->addcategory) { ?>
    			<a href="<?php echo $this->addcategory; ?>"><?php echo $this->translate('Categories');?></a><span></span>
    		<?php }?>    	
    		<?php if($this->reorderlink) { ?>
    			<a id="hrefReorder" href="<?php echo $this->reorderlink; ?>"><?php echo $this->translate('Reorder');?></a><span></span>
    		<?php }?>
    		<a href="<?php echo $this->addlink; ?>"><?php echo ($this->translate('Add New'))?></a><span></span>
        <?php if($this->publishlink && isset(Standard_Functions::getCurrentUser()->user_group) && Standard_Functions::getCurrentUser()->user_group == "Administrator") { ?>
        <a class="module_publish" href="<?php echo $this->publishlink; ?>"><?php echo ($this->translate('Publish'))?></a><span></span>
        <?php } ?>
    	</div>
    <?php 
	} ?>
  </header>
  <!-- #header-->
  <div style="clear:both;"></div>
  <div id="content">
    <?php echo $this->layout ()->content; ?>
    <br style="clear:both" />
  </div>
  <!-- #content-->
  
  <footer id="footer">
  	<?php echo $this->translate('Powered by:')?> <a href = "http://prostart.ch">prostart consulting gmbh</a>
    <div style="float:right" id="footer-version">
      <a class="versionPopup">
        <?php
        $version = Standard_Functions::getVersion();
        if(!empty($version)){
          echo "Version Release".$version[0]["version_number"];
        }
        ?>
      </a>
    </div>
    <div id="versionDetails" style="display:none">
      <!-- Version will appended here -->
    </div>
  </footer>
  <!-- #footer --> 
</div>
<!-- #wrapper -->
<script type="text/template" id="versionLayout">
<div style="float:left">
  <div class="versionTitle">
    <b>Version:</b>
  </div>
  <div class="versionDescription">
    <span>{{version_number}}</span>
  </div>
</div>

<div style="float:left">
  <div class="versionTitle">
    <b>Title:</b>
  </div>
  <div class="versionDescription">
    <span>{{title}}</span>
  </div>
</div>

<div style="float:left">
  <div class="versionTitle">
    <b>Description:</b>
  </div>
  <div class="versionDescription">
    <span>{{{description}}}</span>
  </div>
</div>

<div style="float:left">
  <div class="versionTitle">
    <b>Category:</b>
  </div>
  <div class="versionDescription">
    <span>{{category}}</span>
  </div>
</div>
<?php if(count($version) > 1){?>
<div class="loadMoreVersion">
  <a class="moreVersion"> <i>Show Previous Version</i> </a>
</div>
<?php } ?>
</script>
<script type="text/javascript">
// <!--
 window.baseUrl = '<?php echo $this->uploadimagelink; ?>';
	function changeLocale(language_id) {
		var promptus = false;
		$(document).queue(function(next){
			promptus = new prompt({
            	reference : $("body"),
                element : "#content",
                beforeShow : function(){
	                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Changing language, please wait')?>");
                }
            });
            next();
		}).queue(function(next){
			$.ajax({
				type : "POST",
				cache : false,
				data : {'language_id':language_id},
				url : "<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'change-locale'),"default",true);?>",
				success : function(json){
					if(json["errors"] != undefined){
						promptus.showErrorMessage("<?php echo $this->translate('Error while changing language.')?>");
						next();
					} else {
						location.href = location.href;
					}
				},
				error : next
  			});
		}).queue(function(next){
			promptus.close();
			next();
  		});
	}
  var template = $('#versionLayout').html();
  var data = {
        version_number:"<?php echo $version[0]['version_number'] ?>",
        title:"<?php echo $version[0]['title'] ?>",
        description:"<?php echo str_replace (array("\r\n", "\n", "\r"), ' ', $version[0]['description'])//echo $version[0]['description'] ?>",
        category:"<?php echo $version[0][category] ?>"
  }
  var output = Mustache.render(template,data);
  $("#versionDetails").append(output);
  $(".versionPopup").on("click",function(){
    $("#versionDetails").dialog({
      modal:true,
      width:450,
      resizable:false,
      title:"Version Details"
    });
  });
  $(".moreVersion").on("click",function(){
    $(document).queue(function(next){
      promptus = new prompt({
        element:'#versionDetails',
        beforeShow : function(){
           this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Getting version history..')?>");
        }
      });
      next();
    }).queue(function(next){
      $.ajax({
        type:"POST",
        dataType:"json",
        cache:false,
        url:'<?php echo $this->baseUrl('/default/index/get-version-details'); ?>',
        success:function(data){
          var template = $('#versionLayout').html();
          $("#versionDetails").html("");
          for(x in data){
            obj = data[x];
            var versionDetails = {
              version_number:obj.version_number,
              title:obj.title,
              description:obj.description,
              category:obj.category
            };
            var output = Mustache.render(template,versionDetails);
            $("#versionDetails").append(output);
          }
          $("#versionDetails").find(".moreVersion").html("<hr>");
          $(".loadMoreVersion").css("width","100%");
          $("#versionDetails").css("height","250px");
          $("#versionDetails").css("overflow-y","scroll");
        }
      });
    });
  });
// -->
</script>
</body>
</html>