<?php $form = $this->form; ?>
<div class="boxBorderBottom">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Add Translation');?> </h2></td>
        </tr>
      </table>
</div>
<div id="filterBox">
<form id="form1" class="zend_form">
	<table>
		<!-- Module Name -->
		<tr>
	    	<td><?php echo $this->translate('Module Name');?></td>
	        <td>
	        	<select name="module_name" id="sel_module_name">
                	<option value="global">Global</option>
                	<?php 
                	foreach($this->modules as $key => $module) {
						?>
						<option value="<?php echo $key; ?>"><?php echo $module; ?></option>
						<?php 
					}
                	?>
                </select>
			</td>
		</tr>
		<?php 
	    	foreach($this->languages as $lang) {
			$required = ($lang["lang"]!="en")? "" : 'required="required"';
		?>
			<tr>
	    		<td>
	    			<?php echo $lang["title"]; ?>
	    		</td>
	    		<td>
	    			<input type="text" name='lang_<?php echo $lang["lang"]; ?>' value="" <?php echo $required; ?> />
	    		</td>
	    	</tr>
		<?php 
			}
	    ?>
		<tr>
			<td align="center" colspan="2">
				<input type="submit" name="submit" id="submit" value="Submit" />&nbsp;
				<input type="reset" name="reset" id="reset" value="Reset" />
			</td>
		</tr>
	</table>
</form>
</div>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$("#form1").validator().submit(function(e){
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#form1",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("Saving Translation...");
	                }
	            });
	            next();
			}).queue(function(next){
				jQuery.ajax({
					url: "<?php echo $this->url(array("module"=>"admin","controller"=>"translation","action"=>"add"),null,true); ?>",
					type:"POST",
					dataType:"json",
					data:form.serialize(),
					success:function(data){
						if(!data.error)
						{
							promptus.showSuccessMessage("Translation saved successfully.");
		                	setTimeout(function(){
		                		promptus.close();
		                		location.href = "<?php echo $this->url(array("module"=>"admin","controller"=>"translation","action"=>"index"),null,true); ?>";
		                    }, 2000);
						}
						else {
							promptus.showErrorMessage(data.message);
							setTimeout(function(){
								promptus.close();
								next();
		                    }, 2000);
						}
					},
					error : next
				});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
	$("#reset").on("click",function(){
		location.href=location.href;
	});
});
// -->
</script>