<form id="frmFilter">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Filter');?></h2></td>
          <td>
          	<table>
              <tr>
                <td><?php echo $this->translate('Module Name');?></td>
                <td>
                <select name="module_name" id="sel_module_name">
                	<option value="global">Global</option>
                	<?php 
                	foreach($this->modules as $key => $module) {
						?>
						<option value="<?php echo $key; ?>"><?php echo $module; ?></option>
						<?php 
					}
                	?>
                </select>
                </td>
                <td><?php echo $this->translate('Language');?></td>
                <td>
                <select name="language" id="sel_language">
                	<?php 
                	foreach($this->languages as $lang) {
						if($lang["lang"]!="en") {
						?>
						<option value="<?php echo $lang["lang"]; ?>"><?php echo $lang["title"]; ?></option>
						<?php 
						}
					}
                	?>
                </select>
                </td>
                <td>&nbsp;</td>
				<td><input type="submit" name="button" id="button" class="button" value="<?php echo $this->translate('Submit');?>">&nbsp;
				<input type="button" name="button" id="btnSave" class="button" value="<?php echo $this->translate('Save');?>">
				</td>
              </tr>
            </table>
          </td>
          
        </tr>
      </table>
</div>
</form>
<form id="frmTranslation">
<input type="hidden" name="module_name" id="module_name" />
<input type="hidden" name="lang" id="lang" />
<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
	        <th scope="col"><?php echo $this->translate('Original');?></th>
		    <th scope="col"><?php echo $this->translate('Translation');?></th>
		</tr>
    </thead> 
	<tbody>
		<tr>
			<td colspan="2" class="dataTables_empty"><?php echo $this->translate('Loading data from server');?></td>
		</tr>
	</tbody>      
</table>
</form>
<script type="text/javascript">
var grid ="";
$(document).ready(function() {

	grid = dataTable({
		"aoColumns": [
						{ "sName": "original","bSortable": false},
						{ "sName": "translation","bSortable": false}
					 ],
		id : $('#dataGrid'),
		filterForm : $('#frmFilter'),
		charLimit : [45,0],
		sAjaxSource: "<?php echo $this->url(array("module"=>"admin","controller"=>"translation","action"=>"grid"));?>"
	});
    $(document).on("submit","#frmFilter",function(){
    	grid.fnDraw();
    	return false;
    });
    $("#btnSave").on("click",function(e){
    	var form = $('#frmTranslation');
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				$("#module_name").attr("value",$("#sel_module_name").attr("value"));
				$("#lang").attr("value",$("#sel_language").attr("value"));
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("Saving Translation...");
	                }
	            });
	            next();
			}).queue(function(next){
				jQuery.ajax({
					url: "<?php echo $this->url(array("module"=>"admin","controller"=>"translation","action"=>"save"),null,true); ?>",
					type:"POST",
					dataType:"json",
					data:form.serialize(),
					success:function(data){
						if(!data.error)
						{
							promptus.showSuccessMessage("Translation saved successfully.");
		                	setTimeout(function(){
		                		promptus.close();
		                		grid.fnDraw();
		                		next();
		                    }, 2000);
						}
						else {
							promptus.showErrorMessage(data.message);
							setTimeout(function(){
								promptus.close();
								next();
		                    }, 2000);
						}
					},
					error : next
				});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();	
		}
    });
});
</script>