<?php $form = $this->form;?>
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditBusinessType" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>">
	<?php echo $form->business_type_id->renderViewHelper()?>
	<table style="margin:10px 0;" class="tableFormtopBottom">
		<tbody>
			<tr>
		    	<td><label for="<?php echo $form->name->getId();?>"><?php echo $form->name->getLabel();?></label></td>
		        <td>
		        	<?php echo $form->name->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td></td>
		        <td>
		        	<?php echo $form->submit->renderViewHelper() ?>&nbsp;
					<?php echo $form->reset->renderViewHelper() ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<script type="text/javascript">
<!--
$(document).ready(function() {
	$("#frmAddEditBusinessType").validator().submit(function(e){
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("Saving Business Type...");
	                }
	            });
	            next();
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize(),
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
							next();
						} else if(json["success"] != undefined){
							promptus.showSuccessMessage("Business Type saved successfully.");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"admin","controller"=>"business-type","action" => "index"),"default",true);?>";
							}, 2000);
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
});
-->
</script>