<?php $form = $this->form; ?>
<div class="boxBorderBottom">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td><?php echo $this->partial($this->partial,array("password"=>$this->password)); ?></td>
        </tr>
      </table>
</div>
<div id="filterBox">
<form id="form1">
	<?php echo $form->system_user_id->renderViewHelper() ?>
	<table class="tableFormtopBottom" style="margin:10px 0;">
		<tr>
	    	<td><?php echo $form->email->renderLabel() ?></td>
	        <td>
	        	<?php echo $form->email->renderViewHelper(); ?>
			</td>
		</tr>
	    <tr>
	    	<td><?php echo $form->password->renderLabel() ?></td>
	        <td>
	        	<?php echo $form->password->renderViewHelper() ?>
			</td>
		</tr>
		<tr>
	    	<td><?php echo $form->confirm_password->renderLabel() ?></td>
	        <td>
	        	<?php echo $form->confirm_password->renderViewHelper() ?>
			</td>
		</tr>
	    <tr>
	    	<td><?php echo $form->role->renderLabel() ?></td>
	        <td>
	        	<?php echo $form->role->renderViewHelper() ?>
	        </td>
		</tr>
		<tr>
			<td></td>
	        <td>
	        	<?php echo $form->submit->renderViewHelper() ?>&nbsp;
				<?php echo $form->reset->renderViewHelper() ?>
	        </td>
		</tr>
		<tr>
			<td colspan="2">
				
			</td>
		</tr>
	</table>
</form>
</div>

<script type="text/javascript">
// <!--
$(document).ready(function() {
	$("#form1").validator().submit(function(e){
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#form1",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving User..')?>");
	                }
	            });
	            next();
			}).queue(function(next){
				jQuery.ajax({
					url: "<?php echo $this->url(array("module"=>"admin","controller"=>"system-user","action"=>"save"),null,true); ?>",
					type:"POST",
					dataType:"json",
					data:form.serialize(),
					success:function(data){
						if(!data.error)
						{
							promptus.showSuccessMessage("<?php echo $this->translate('User saved successfully.')?>");
			            	setTimeout(function(){
			            		promptus.close();
			            		location.href = "<?php echo $this->url(array("module"=>"admin","controller"=>"system-user","action"=>"index"),null,true); ?>";
			            		next();
			                }, 2000);
						} else {
							promptus.showErrorMessage(data.message);
							setTimeout(function(){
								promptus.close();
								next();
			                }, 2000);
						}
					},
					error: function(){
						promptus.showErrorMessage("<?php echo $this->translate('Error occured') ?>");
						setTimeout(function(){
							promptus.close();
							next();
			            }, 2000);
					}
				});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
});
// -->
</script>