<?php $form = $this->form;?>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxcore.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/gettheme.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxdropdownbutton.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxscrollbar.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxbuttons.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxtree.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxpanel.js"); ?>"></script>
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
          <td align="right"><h2><?php echo $this->language; ?></h2></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditDocumentCategory" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php echo $form->module_document_category_id->renderViewHelper(); ?>
	<?php echo $form->module_document_category_detail_id->renderViewHelper(); ?>
	<?php echo $form->language_id->renderViewHelper(); ?>
	<?php echo $form->parent_id->renderViewHelper(); ?>
	<table style="margin:10px 0;">
		<tbody>
			<tr>
				<td><label for="tree"><?php echo $this->translate('Select Category:'); ?></label></td>
				<td>
					<div id='jqxWidget'>
						<div id="dropDownButton">
							<div id='jqxTree'></div>
						</div>
					</div>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->title->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->title->renderViewHelper()?>
				</td>
			</tr>
			
			<tr>
				<td valign="top">
					<label><?php echo $this->translate('Icon:')?></label>
				</td>
				<td valign="top">
					<div id="lstLogo" class="logo-box">
        				<?php $resource_path = $this->baseUrl("resource/document/preset-icons");?>
        				<?php foreach ($this->iconpack as $icon):?>
        				<div class="">
							<label for="selLogo_<?php echo $icon; ?>">
								<img src="<?php echo $resource_path . "/" . $icon; ?>" width="64" />
							</label>
							<input type="radio" id="selLogo_<?php echo $icon; ?>" name="selLogo" value="<?php echo $icon; ?>" />
						</div>
        				<?php endforeach;?>
					</div>
				</td>
			</tr>
			<tr>
		        <td>&nbsp;</td>
			    <td>
		        	<div class="logo-box">
		        		<table>
    						<tr>
    							<td>
    								<?php 
    								$icon_path = $this->baseUrl("resource/document/");
    					        	if($this->icon_src!="") {
    					        	?>
    					        	<img class="iconImage" alt="" src="<?php echo $icon_path."/".$this->icon_src;?>" style="width: 64px;" />
    					        	<?php 
    					        	}
    					        	?>
    				        	</td>
    				        	<td>
    				        		<?php
    				        		$checked = "";
    					        	if($this->icon_src!="") {
    					        		$checked = "checked='checked'";
    								}
    								?>
    					        	
    								<input type="radio" id="selLogo_0" checked="checked" name="selLogo" value="0" style="margin-left: 10px;" />
    								<label for="selLogo_0"><?php echo $this->translate('Upload:')?></label>
    								<input id="icon" type="file" name="icon" /> (Size: 120px &#215; 120px )
    					        	<input id="icon_path" type="hidden" name="icon_path" value="" />
    				        	</td>
    			        	</tr>
			        	    <tr id="deleteIconButton">
    			        	 <?php if($this->icon_src!=""){ ?>
    						    <td>
    							    <div class="deletebuttons"><a class="deleteIcon red button-grid">Delete</a></div>
    						    </td>
    					    </tr>
					    <?php } ?>
			        	</table>
					</div>
				</td>
			</tr>
			
			<tr>
		    	<td><?php echo $form->status->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->status->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		        <td colspan="3" align="center">
		        	<?php echo html_entity_decode($form->submit->renderViewHelper()) ?>&nbsp;
		        	<?php echo (Standard_Functions::$action == "edit")? html_entity_decode($form->applyallcat->renderViewHelper()):""?>&nbsp;
					<?php echo html_entity_decode($form->reset->renderViewHelper()) ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$("#applyallcat").on("click",function(e){
		if(!e.isDefaultPrevented()){
	    	var promptus = new prompt({
	            	reference :"#frmAddEditDocumentCategory",
	                element : "#content",
	                message : "<?php echo $this->translate('Your changes will be saved and applied to all languages. Is it Ok?'); ?>",
	                buttons : {
	                    "Yes" : function(self){
	                        $("#frmAddEditDocumentCategory").trigger("submit",{all:true});
	                    },
	                    "No"  : function(self){
	                    	this.close();
	                    },
	                }
	            });
	        e.preventDefault();
	    }
	});
	var parentIdLabel = "<?php echo $this->parentCategory; ?>";
	var data = <?php echo $this->categoryTree; ?>;
	//console.log(data);
	//creating data which jqtree plugin can use
	var builddata = function () {
		var source = [];
		var items = [];	
		// build hierarchical source.
		items[0]={id:0,label:'Root',selected:false};
		source[0] = items[0];
		for (var i = 0; i < data.length; i++) {
			var item = data[i];
			var label = item["text"];
			var parentid = item["parentId"];
			var id = item["id"];

			if (items[parentid]) {
				var item = { id: id, label: label, item: item };
				if (!items[parentid].items) {
					items[parentid].items = [];
				}
				items[parentid].items[items[parentid].items.length] = item;
				items[id] = item;
			}
			else {
				items[id] = { id: id, label: label, item: item };
				source[id] = items[id];
			}
		}		
		return source;
	}
	$("input:radio[name=selLogo]").on("change",function(){
		if($('input:radio[name=selLogo]:checked').val() == 0)
		{
			$("#icon").removeAttr("disabled");
		} else {
			$("#icon").attr("disabled","disabled");
		}			
	});
	$(".deleteIcon").on("click",function(){
    	$("#icon_path").attr("value","deleted");
    	$(".iconImage").remove();
    	$("#icon").attr("value","");
    	$("tr#deleteIconButton").remove();
    });
	$("#dropDownButton").jqxDropDownButton({ width: 150, height: 25 });
	$('#jqxTree').bind('initialized', function (event) { 
		var args = event.args;
		parentIdLabel = (parentIdLabel=="")?"Root":parentIdLabel;
    	var dropDownContent = '<div style="position: relative; margin-left: 3px; margin-top: 5px;">' + parentIdLabel + '</div>';
    	$("#dropDownButton").jqxDropDownButton('setContent', dropDownContent);
    });	
	$('#jqxTree').bind('select', function (event) {
        var args = event.args;
        var item = $('#jqxTree').jqxTree('getItem', args.element);
        $("#parent_id").attr("value",item.id);
        var dropDownContent = '<div style="position: relative; margin-left: 3px; margin-top: 5px;">' + item.label + '</div>';
        $("#dropDownButton").jqxDropDownButton('setContent', dropDownContent);
    });
	$('#jqxTree').bind('click', function (event) {
		$("#dropDownButton").jqxDropDownButton("close");
	});
    var source = builddata();
    //console.log(source);
    $("#jqxTree").jqxTree({source:source,width: 250 });
    $('#jqxTree').jqxTree('expandAll');
	$("#frmAddEditDocumentCategory").validator().submit(function(e,customObject){
		customObject = customObject || {};
		var queryAppend = "";
		if(customObject.all){
			queryAppend = "&all=true";
		}
		var orignalParentId = <?php echo ($this->orignalParent != "")?$this->orignalParent:"''" ?>;
		var currentParentId = $("#parent_id").val();
		if(orignalParentId != currentParentId){
			var parent = '&parent=changed';
		}else{
			var parent = '&parent=intact';
		}
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Document Category...')?>");
	                }
	            });
	            next();
			}).queue(function(next){
				if($('input:radio[name=selLogo]:checked').val() == 0 && $('#icon').attr("value")!="") {
					$.ajaxFileUpload({
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:'icon',
						dataType: 'json',
						data:{iconupload:'true'},
						success: function (data, status)
						{
							if(data.success != undefined) {
								$("#icon_path").attr("value",data.success);
								next();
							}
						},
						error: function (data, status, e)
						{
							promptus.showErrorMessage("<?php echo $this->translate('Error uploading icon.')?>");
							setTimeout(function(){
								promptus.close();
							}, 2000);
							
						}
					});
				} else {
					next();
				}
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize() + queryAppend + parent,
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
							next();
						} else if(json["success"] != undefined){
							promptus.showSuccessMessage("<?php echo $this->translate('Document Category saved successfully.')?>");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"document","controller"=>"category","action" => "index"),"default",true);?>";
							}, 2000);
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
});
// -->
</script>