<script type="text/javascript" src="<?php echo $this->baseUrl("libs/tinymce/js/tiny_mce.js"); ?>"></script>
<script type="text/javascript">
var tinyMCEParams = {
		// General options
		mode : "textareas",
		theme : "advanced",
		plugins : "autolink,lists,pagebreak,style,layer,table,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,visualblocks",

		// Theme options
		theme_advanced_buttons1 : "forecolor,backcolor,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
		theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview",
		theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
		theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks",
		
		//plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,visualblocks",
		//plugins : "paste,pagebreak,table",
		
		// Theme options
		//theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,undo,redo,|,bullist,numlist,|,outdent,indent,blockquote,|,forecolor,backcolor,|,tablecontrols,|,hr",
		//theme_advanced_buttons1 : "formatselect,fontselect,fontsizeselect,|,forecolor,backcolor,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,code",
		//theme_advanced_buttons2 : "",
		//theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,ltr,rtl",
		//theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,pagebreak",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : false,
		height: "350",
		apply_source_formatting : true,
		remove_linebreaks: false,
		// Example content CSS (should be your site CSS)
		content_css : "<?php echo $this->baseUrl("libs/tinymce/css/content.css"); ?>",

		// Drop lists for link/image/media/template dialogs
		template_external_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/template_list.js"); ?>",
		external_link_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/link_list.js"); ?>",
		external_image_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/image_list.js"); ?>",
		media_external_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/media_list.js"); ?>",

		// Style formats
		style_formats : [
			{title : 'Bold text', inline : 'b'},
			{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
			{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
			{title : 'Example 1', inline : 'span', classes : 'example1'},
			{title : 'Example 2', inline : 'span', classes : 'example2'},
			{title : 'Table styles'},
			{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
		],
		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
	};
tinyMCE.init(tinyMCEParams);
</script>
<form id="frmFilter">
<div id="filterBox">
    <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Filter');?></h2></td>
          <td>
            <table>
              <tr>
                <td><?php echo $this->translate('Module Name');?></td>
                <td>
	                <select name="template_name" id="sel_template_name">
	                	<option value="">Select Email Template</option>
	                	<option value="password_reset_admin">Password Reset (Admin)</option>
	                	<option value="welcome_customer">Welcome customer</option>
	                	<option value="welcome_user">Welcome user</option>
	                </select>
                </td>
                <td>&nbsp;</td>
				<td>
					<input type="submit" name="button" id="button" class="button" value="<?php echo $this->translate('Submit');?>">&nbsp;
				</td>
              </tr>
            </table>
          </td>
        </tr>
    </table>
</div>
<div class="boxBorderBottom">
	<table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="top" colspan="2">&nbsp;
          </td>
        </tr>
        <tr>
          <td valign="top" rowspan="2">
          	<textarea id="template-content" name="template-content" rows="25" cols="125" style="width: auto !important;height: auto !important;"></textarea>
          </td>
          <td valign="top">
          	<div id="divTemplateVars">
          		<div class="title">Template Variables</div>
          		<div class="vars"></div>
          	</div>
          </td>
        </tr>
        <tr>
        	<td valign="bottom" align="right">
        		<input type="button" name="button" id="btnSave" class="button" value="<?php echo $this->translate('Save');?>">
        	</td>
        </tr>
        <tr>
          <td valign="top" colspan="2">&nbsp;
          </td>
        </tr>
    </table>
</div>
</form>
<script type="text/javascript">
$(document).ready(function() {

	$("#button").on("click",function(e){
    	if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : $("#content"),
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("Loading email template...");
	                }
	            });
	            next();
			}).queue(function(next){
				var temp_name = $("#sel_template_name").attr("value");
				jQuery.ajax({
					url: "<?php echo $this->url(array("module"=>"admin", "controller"=>"email-template", "action"=>"load-template"),null,true); ?>",
					type:"POST",
					dataType:"json",
					data: {template_name: temp_name},
					success:function(data){
						if(!data.error)
						{
							// Load data
							$("#template-content").html(data.message.content);
							$("#divTemplateVars .vars").html(data.message.template_vars);

							var ed = tinyMCE.get('template-content');
					        ed.setProgressState(1); // Show progress
					        ed.setProgressState(0); // Hide progress
					        ed.setContent(data.message.content);

							// Add Events To template-var
							$(".template-var a").click(function(e){
								if(!e.isDefaultPrevented()){
									tinyMCE.execInstanceCommand("template-content","mceInsertContent",false,$(this).text());
									e.preventDefault();
								}
							}); 
							next();
						}
						else {
							promptus.showErrorMessage(data.message);
							setTimeout(function(){
								promptus.close();
								next();
		                    }, 2000);
						}
					},
					error : next
				});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();	
		}
    	return false;
    });
    $("#btnSave").on("click",function(e){
    	var form = $('#frmTranslation');
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				$("#module_name").attr("value",$("#sel_module_name").attr("value"));
				$("#lang").attr("value",$("#sel_language").attr("value"));
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("Saving Template...");
	                }
	            });
	            next();
			}).queue(function(next){
				var temp_name = $("#sel_template_name").attr("value");
				var ed = tinyMCE.get('template-content');
				var temp_content = ed.getContent();
				jQuery.ajax({
					url: "<?php echo $this->url(array("module"=>"admin","controller"=>"email-template","action"=>"save"),null,true); ?>",
					type:"POST",
					dataType:"json",
					data: {template_name: temp_name, content:temp_content},
					success:function(data){
						if(!data.error)
						{
							promptus.showSuccessMessage("Template saved successfully.");
		                	setTimeout(function(){
		                		promptus.close();
		                		next();
		                    }, 2000);
						}
						else {
							promptus.showErrorMessage(data.message);
							setTimeout(function(){
								promptus.close();
								next();
		                    }, 2000);
						}
					},
					error : next
				});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();	
		}
    });
});
</script>