<?php $form = $this->form; ?>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/tinymce/js/tiny_mce.js"); ?>"></script>
<script type="text/javascript">
tinyMCE.init({
	// General options
	mode : "textareas",
	theme : "advanced",
 	convert_newlines_to_brs: false,
	plugins : "autolink,lists,pagebreak,style,layer,table,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,visualblocks",

	// Theme options
	theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
	theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
	theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
	theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks",
	
	// set value of textarea if null
	//onchange_callback : "textAreaValueChange",

	//plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,visualblocks",
	//plugins : "paste,pagebreak,table",
	
	// Theme options
	//theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,undo,redo,|,bullist,numlist,|,outdent,indent,blockquote,|,forecolor,backcolor,|,tablecontrols,|,hr",
	//theme_advanced_buttons1 : "formatselect,fontselect,fontsizeselect,|,forecolor,backcolor,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,code",
	//theme_advanced_buttons2 : "",
	//theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,ltr,rtl",
	//theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,pagebreak",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
	theme_advanced_resizing : false,

	// Example content CSS (should be your site CSS)
	content_css : "<?php echo $this->baseUrl("libs/tinymce/css/content.css"); ?>",

	// Drop lists for link/image/media/template dialogs
	template_external_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/template_list.js"); ?>",
	external_link_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/link_list.js"); ?>",
	external_image_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/image_list.js"); ?>",
	media_external_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/media_list.js"); ?>",

	// Style formats
	style_formats : [
		{title : 'Bold text', inline : 'b'},
		{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
		{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
		{title : 'Example 1', inline : 'span', classes : 'example1'},
		{title : 'Example 2', inline : 'span', classes : 'example2'},
		{title : 'Table styles'},
		{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
	],
	// Replace values for the template plugin
	template_replace_values : {
		username : "Some User",
		staffid : "991234"
	}
});
//function textAreaValueChange(inst){
	//content_textarea.value = tinyMCE.get('content_textarea').getContent();
//}
</script>
<div id="filterBox">
	<table
		style="width: 100%; border: 0; border-spacing: 0; border-collapse: collapse;">
		<tr>
			<td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
			<td align="right"><h2><?php echo $this->language; ?></h2></td>
		</tr>
	</table>
</div>
<div class="boxBorderBottom">
	<form id="frmAddEditVersion" method="<?php echo $form->getMethod();?>"
		action="<?php echo $form->getAction();?>" class="zend_form">
	<table style="margin: 10px 0;">
			<tbody>
				<tr>
					<td>
						<?php echo $form->version_id->renderViewHelper() ?>
						<?php echo $form->version_detail_id->renderViewHelper() ?>
						<?php echo $form->title->renderLabel() ?>
					</td>
					<td>
		        		<?php echo $form->title->renderViewHelper()?>
					</td>
				</tr>
				<tr>
					<td>
						<?php echo $form->version_number->renderLabel() ?></td>
					<td>
		        		<?php echo $form->version_number->renderViewHelper()?>
					</td>
				</tr>
				<tr>
					<td>
						<?php echo $form->description->renderLabel() ?></td>
					<td>
		        		<?php echo $form->description->renderViewHelper()?>
					</td>
				</tr>
				<tr>
					<td>
						<?php echo $form->category->renderLabel() ?></td>
					<td>
		        		<?php echo $form->category->renderViewHelper()?>
					</td>
				</tr>
				<tr>
					<td>
						<?php echo $form->created_at->renderLabel() ?></td>
					<td>
		        		<?php echo $form->created_at->renderViewHelper()?>
					</td>
				</tr>
				<tr>
					<td><?php echo $form->status->renderLabel() ?></td>
					<td><?php echo $form->status->renderViewHelper()?></td>
				</tr>
				<tr>	
					<td colspan="3" align="center">
		        	<?php echo html_entity_decode($form->submit->renderViewHelper()) ?>&nbsp;
		        	<?php echo Standard_Functions::$action == "edit"?html_entity_decode($form->applyall->renderViewHelper()):""?>&nbsp;
					<?php echo html_entity_decode($form->reset->renderViewHelper())?>
					</td>
				</tr>
			</tbody>
		</table>
	</form>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('#created_at').datetimepicker({ 
		showOn: "both",
		buttonImage: "<?php echo $this->baseUrl("images/calander.png");?>",
		buttonImageOnly: true,
		dateFormat: 'dd/mm/yy', 
		showSecond: false,
		timeFormat: 'hh:mm',
		firstDay:1
	});
	$("#applyall").on("click",function(e){
		if(!e.isDefaultPrevented()){
	    	var promptus = new prompt({
	            	reference :"#frmAddEditVersion",
	                element : "#content",
	                message : "<?php echo $this->translate('Your changes will be saved and applied to all languages. Is it Ok?'); ?>",
	                buttons : {
	                    "Yes" : function(self){
		                    this.close();
	                        $("#frmAddEditVersion").trigger("submit",{all:true});
	                    },
	                    "No"  : function(self){
	                    	this.close();
	                    },
	                }
	            });
	        e.preventDefault();
	    }
	});
	$("#frmAddEditVersion").validator().submit(function(e,customObject){
		customObject = customObject || {};
		var queryAppend = "";
		if(customObject.all){
			queryAppend = "&all=true";
		}
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("Saving Version...");
	                }
	            });
	            next();
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize() + queryAppend,
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
							next();
						} else if(json["success"] != undefined){
							promptus.showSuccessMessage("Version saved successfully.");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"admin","controller"=>"version","action" => "index"),"default",true);?>";
							}, 2000);
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
});
</script>