<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxcore.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/gettheme.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxdropdownbutton.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxscrollbar.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxbuttons.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxtree.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/jqwidget/js/jqxpanel.js"); ?>"></script>

<?php $data = $this->data; ?>
<form id="frmFilter">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
			<td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Reorder Events Types'); ?></h2></td>
			<td align="right">
          		<input type="submit" name="button" id="save-order" class="button" value="<?php echo $this->translate('Save')?>" />
          		<input type="reset" name="reset" id="reset" class="button" value="<?php echo $this->translate('Reset')?>" />
			</td>
        </tr>
      </table>
</div>
</form>
<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
			<th scope="col"><?php echo $this->translate('Title'); ?></th>
		    <th scope="col"><?php echo $this->translate('Status'); ?></th>
		</tr>
    </thead> 
	<tbody>
		<?php 
			if(count($data)==0) {
		?>
			<tr>
				<td colspan="2">No records found</td>
			</tr>
		<?php
			}
			foreach($data as $row) {
		?>
			<tr id="index-<?php echo $row["dc.contact_types_id"];?>" class="sortable" style="cursor: move;">
				<td><?php echo $row['dcd.title']; ?></td>
			    <td><?php echo ($row['dc.status']==1)? "Active" : "Inactive"; ?></td>
			</tr>
		<?php } ?>
	</tbody>      
</table>

<script type="text/javascript">
$(document).ready(function() {
	window.dragStartIndex = 0;
	//  $(".sortable:eq(1)").insertBefore($(".sortable:eq(0)"));
	$(".sortable").on("mousedown",function(){
		window.dragStartIndex = $(this).index(".sortable") + 1;
		$(this).addClass("drag-start");
	});
	$(".sortable").on("mouseup",function(){
		if(window.dragStartIndex>0 && window.dragStartIndex != ($(this).index(".sortable") + 1)) {
			var fromIndex = window.dragStartIndex - 1;
			var toIndex = $(this).index(".sortable");
			if(fromIndex > toIndex) {
				$(".sortable:eq("+fromIndex+")").insertBefore($(".sortable:eq("+toIndex+")"));
			} else {
				$(".sortable:eq("+fromIndex+")").insertAfter($(".sortable:eq("+toIndex+")"));
			}
		}
	});
	$("#dataGrid").on("mouseup",function(){window.dragStartIndex = 0; $(".sortable").removeClass("drag-start");});
	$("#dataGrid").on("mousedown",function(){return false;});

	$(document).on("click","#save-order",function(e){
        var self = this;
        window.currentDeleteUrl = location.href; 
        if(!e.isDefaultPrevented()){
        	var promptus = new prompt({
                    	reference : self,
                        element : "#content",
                        message : "<?php echo $this->translate('Are you sure you want to save contact types order?'); ?>",
                        buttons : {
                            "Yes" : function(self){
                                var prompt = this;
                                $(document).queue(function(next){
                                    prompt.showLoadingMessage("<?php echo $this->translate('Please wait while saving contact types order..'); ?>");
                                    next();
                                }).queue(function(next){
                                    $.ajax({
                                        url: window.currentDeleteUrl,
                                        cache: false,
                                        type: "POST",
                                        dataType: "json",
                                        data: serializeOrder(),
                                        success: function(json){
                                            if(json.success != undefined){ 
                                            	prompt.showSuccessMessage("<?php echo $this->translate('Contact types reordered successfully.'); ?>");
                                            	setTimeout(function(){
                    								location.href = "<?php echo $this->url(array("module"=>"contact","controller"=>"types","action" => "index"),"default",true);?>";
                    							}, 2000);
                                            } else if(json.errors != undefined){
                                                var errorMessage = "<?php echo $this->translate('Unable to reorder contact types:'); ?><br />";
                                                errorMessage += json.errors.message;
                                            	prompt.showErrorMessage(errorMessage);
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 2000);
                                            }
                                        },
                                        error: function(){
                                        }
                                    }).complete(next); 
                                });
                            },
                            "No"  : function(self){
                            	this.close();
                            },
                        }
                    });
            e.preventDefault();
        }
    });
    
	$("#reset").on("click", function(){
		location.href = location.href;
	});

});
function serializeOrder(){
	var response = {order:{}};
	$(".sortable").each(function(){
		var index = ($(this).attr("id") + "").replace("index-","");
		response["order"][$(this).index(".sortable")+1] = index;
	});
	return response;
}
document.onselectstart = function() {return false;}
</script>