<form id="frmFilter">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Filter');?></h2></td>
          <td>
          	<table>
              <tr>
                <td><?php echo $this->translate('Customer Name');?></td>
                <td><input type="text" name="customer_name" class="input" id="txtCustomerName" /></td>
                <td><?php echo $this->translate('Edit Template');?></td>
                <td>
                	<input type="text" name="bt[name]" class="input" id="txtBusinessTypeId" />
                </td>
                <td><?php echo $this->translate('Status');?></td>
                <td>
                	<select name="c[status]">
                		<option value="1"><?php echo $this->translate('Active');?></option>
                		<option value="0"><?php echo $this->translate('InActive');?></option>
                	</select>
                </td>
                <td>&nbsp;</td>
                <td><input type="submit" name="button" id="button" class="button" value="<?php echo $this->translate('Submit');?>&nbsp;"></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
</div>
</form>
<a class="togglefilter"></a>
<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
	        <th scope="col"><?php echo $this->translate('App Access ID');?></th>
		    <th scope="col"><?php echo $this->translate('Business Type');?></th>
		    <th scope="col"><?php echo $this->translate('Customer User Name');?></th>
		    <th scope="col"><?php echo $this->translate('Customer Name');?></th>
		    <th scope="col"><?php echo $this->translate('Template Name');?></th>
		    <th scope="col"><?php echo $this->translate('Status');?></th>
		    <th scope="col"><?php echo $this->translate('Action');?></th>
		</tr>
    </thead> 
	<tbody>
		<tr>
			<td colspan="7" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>      
</table>

<script type="text/javascript">
var grid ="";
$(document).ready(function() {
	grid = dataTable({
		aaSorting: [[ 0, "desc" ]],
		"aoColumns": [
						{ "sName": "app_access_id" },
						{ "sName": "bt.name" },
						{ "sName": "u.username" },
						{ "sName": "customer_name" },
						{ "sName": "t.name" },
						{ "sName": "c.status" },
						{ "sName": "actions","bSortable": false}
					 ],
		id : $('#dataGrid'),
		filterForm : $('#frmFilter'),
		charLimit : [0,20,20,35,20,0],
		sAjaxSource: "<?php echo $this->url(array("module"=>"admin","controller"=>"customer","action"=>"grid"),"default",true);?>",
	});

	$(document).on("click",".grid_delete",function(e){
        var self = this;
        window.currentDeleteUrl = $(this).attr("href"); 
        if(!e.isDefaultPrevented()){
        	var promptus = new prompt({
                    	reference : self,
                        element : ".dataTables_wrapper",
                        message : "Are you sure you want to delete this Customer?",
                        buttons : {
                            "Yes" : function(self){
                                var prompt = this;
                                $(document).queue(function(next){
                                    prompt.showLoadingMessage("Please wait while deleting customer..");
                                    next();
                                }).queue(function(next){
                                    $.ajax({
                                        url: window.currentDeleteUrl,
                                        cache: false,
                                        type: "GET",
                                        dataType: "json",
                                        success: function(json){
                                            if(json.success != undefined){ 
                                            	prompt.showSuccessMessage("Customer deleted successfully.");
                                            	setTimeout(function(){
                                            		prompt.close();
                                                	grid.fnDraw();
                                                }, 1000);
                                            } else if(json.errors != undefined){
                                                var errorMessage = "Unable to delete customer:<br />";
                                                errorMessage += json.errors.message;
                                            	prompt.showErrorMessage(errorMessage);
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 2000);
                                            }
                                        },
                                        error: function(){
                                        }
                                    }).complete(next); 
                                });
                            },
                            "No"  : function(self){
                            	this.close();
                            },
                        }
                    });
            e.preventDefault();
        }
    });
	$('.togglefilter').on("click",function(){
		$('#filterBox').toggle();
		$('#content > a').toggleClass('flip-vertical');
	});
	$('#filterBox').hide();
});
$(document).on("submit","#frmFilter",function(){
	grid.fnDraw();
	return false;
});
</script>